-- 015_replication_event_triggers.sql
--
-- Automatic outbox event emission for policy and tenant changes.
--
-- Secret events are written explicitly by the secret-engine service inside the
-- same application transaction as the secret write.  For policy and tenant
-- updates we cannot touch the policy-engine or identity-service services
-- (owned by other teams) without coordination, so we emit replication events
-- via DB triggers instead.  This keeps the event-emission contract in the
-- storage layer and avoids service-to-service coupling.
--
-- Trigger behaviour:
--   - INSERT or UPDATE on shared.policies  → emits 'policy_update'
--   - INSERT or UPDATE on system.tenants   → emits 'tenant_update'
--   - The REGION_ID session variable (app.region_id) is used as source_region.
--     Services set this on startup.  If not set, 'unknown' is used as a safe
--     fallback so the trigger never prevents writes.
--
-- Payload shapes:
--   policy_update : { tenant_id, name, document, updated_at }
--   tenant_update : { id, slug, display_name, tier, root_key_id,
--                     updated_at, deleted_at }

-- =============================================================================
-- Helper: read the region identifier set by the connecting service.
-- =============================================================================
CREATE OR REPLACE FUNCTION system.current_region_id() RETURNS TEXT
    LANGUAGE sql STABLE
AS $$
    SELECT COALESCE(
        current_setting('app.region_id', true),
        'unknown'
    );
$$;

-- =============================================================================
-- Trigger function: emit policy_update replication event
-- =============================================================================
CREATE OR REPLACE FUNCTION system.trg_emit_policy_replication_event()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER   -- runs with definer's privileges so no BYPASSRLS needed
AS $$
BEGIN
    -- Skip events generated by the replication-agent itself (identified by
    -- the session variable set in apply_policy_update before the upsert).
    -- This prevents replication loops: A → B → A → …
    IF current_setting('app.replication_agent', true) = 'true' THEN
        RETURN NEW;
    END IF;

    INSERT INTO system.replication_events
        (event_type, source_region, payload, vector_clock)
    VALUES (
        'policy_update',
        system.current_region_id(),
        jsonb_build_object(
            'tenant_id',  NEW.tenant_id,
            'name',       NEW.name,
            'document',   NEW.document,
            'updated_at', NEW.updated_at
        ),
        '{}'::jsonb
    );

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_policies_replication
    AFTER INSERT OR UPDATE ON shared.policies
    FOR EACH ROW EXECUTE FUNCTION system.trg_emit_policy_replication_event();

-- =============================================================================
-- Trigger function: emit tenant_update replication event
-- =============================================================================
CREATE OR REPLACE FUNCTION system.trg_emit_tenant_replication_event()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    -- Skip replication-agent-originated writes to prevent loops.
    IF current_setting('app.replication_agent', true) = 'true' THEN
        RETURN NEW;
    END IF;

    INSERT INTO system.replication_events
        (event_type, source_region, payload, vector_clock)
    VALUES (
        'tenant_update',
        system.current_region_id(),
        jsonb_build_object(
            'id',           NEW.id,
            'slug',         NEW.slug,
            'display_name', NEW.display_name,
            'tier',         NEW.tier,
            'root_key_id',  NEW.root_key_id,
            'updated_at',   NEW.updated_at,
            'deleted_at',   NEW.deleted_at
        ),
        '{}'::jsonb
    );

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_tenants_replication
    AFTER INSERT OR UPDATE ON system.tenants
    FOR EACH ROW EXECUTE FUNCTION system.trg_emit_tenant_replication_event();
