//! gRPC service implementation for the lease-manager.
//!
//! Implements the `LeaseService` trait generated by tonic from the
//! `wslvault.lease.v1` proto package. Each handler delegates storage
//! mutations to the injected `LeaseStoreBackend` and returns proto-typed
//! responses.

use std::sync::Arc;

use tonic::{Request, Response, Status};

use crate::store::{LeaseId, LeaseRecord, LeaseState, LeaseStoreBackend};

use proto::lease_service_server::LeaseService;
use proto::{
    GetLeaseRequest, GetLeaseResponse, LeaseInfo, ListLeasesRequest, ListLeasesResponse,
    RenewLeaseRequest, RenewLeaseResponse, RevokeLeaseRequest, RevokeLeaseResponse,
};

pub mod proto {
    tonic::include_proto!("wslvault.lease.v1");
}

/// Concrete gRPC service handler.
#[derive(Clone)]
pub struct LeaseServiceImpl {
    store: Arc<dyn LeaseStoreBackend>,
}

impl LeaseServiceImpl {
    pub fn new(store: Arc<dyn LeaseStoreBackend>) -> Self {
        Self { store }
    }
}

#[tonic::async_trait]
impl LeaseService for LeaseServiceImpl {
    /// Return the full lease record for the given lease ID.
    async fn get_lease(
        &self,
        request: Request<GetLeaseRequest>,
    ) -> Result<Response<GetLeaseResponse>, Status> {
        let req = request.into_inner();
        let lease_id = req
            .lease_id
            .parse::<LeaseId>()
            .map_err(|_| Status::invalid_argument("invalid lease_id format"))?;

        let record = self
            .store
            .get_lease(&lease_id)
            .await
            .ok_or_else(|| Status::not_found(format!("lease not found: {}", lease_id)))?;

        // Compute derived fields before consuming the record by field-moving.
        let remaining_seconds = record.remaining_seconds();
        let response = GetLeaseResponse {
            lease_id: record.id.to_string(),
            tenant_id: record.tenant_id,
            target_type: record.target_type,
            state: record.state.as_str().to_string(),
            ttl_seconds: record.ttl_seconds,
            remaining_seconds,
            renewable: record.renewable,
            issued_at: record.issued_at.to_rfc3339(),
            expires_at: record.expires_at.to_rfc3339(),
        };

        Ok(Response::new(response))
    }

    /// Extend the expiry of an active, renewable lease.
    async fn renew_lease(
        &self,
        request: Request<RenewLeaseRequest>,
    ) -> Result<Response<RenewLeaseResponse>, Status> {
        let req = request.into_inner();
        let lease_id = req
            .lease_id
            .parse::<LeaseId>()
            .map_err(|_| Status::invalid_argument("invalid lease_id format"))?;

        if req.increment_seconds <= 0 {
            return Err(Status::invalid_argument(
                "increment_seconds must be positive",
            ));
        }

        let updated = self
            .store
            .renew_lease(&lease_id, req.increment_seconds)
            .await
            .map_err(|e| Status::failed_precondition(e))?;

        let response = RenewLeaseResponse {
            lease_id: updated.id.to_string(),
            ttl_seconds: updated.ttl_seconds,
            expires_at: updated.expires_at.to_rfc3339(),
        };

        Ok(Response::new(response))
    }

    /// Immediately revoke a lease, transitioning it to the Revoked state.
    async fn revoke_lease(
        &self,
        request: Request<RevokeLeaseRequest>,
    ) -> Result<Response<RevokeLeaseResponse>, Status> {
        let req = request.into_inner();
        let lease_id = req
            .lease_id
            .parse::<LeaseId>()
            .map_err(|_| Status::invalid_argument("invalid lease_id format"))?;

        self.store
            .revoke_lease(&lease_id)
            .await
            .map_err(|e| Status::not_found(e))?;

        Ok(Response::new(RevokeLeaseResponse {}))
    }

    /// List all leases for a tenant with an optional state filter.
    async fn list_leases(
        &self,
        request: Request<ListLeasesRequest>,
    ) -> Result<Response<ListLeasesResponse>, Status> {
        let req = request.into_inner();

        if req.tenant_id.is_empty() {
            return Err(Status::invalid_argument("tenant_id is required"));
        }

        let state_filter = if req.state_filter.is_empty() {
            None
        } else {
            Some(req.state_filter.as_str())
        };

        let records = self
            .store
            .list_leases(&req.tenant_id, state_filter)
            .await;

        let leases: Vec<LeaseInfo> = records
            .into_iter()
            .map(|r| {
                // Compute remaining_seconds before field-moves consume the record.
                let remaining_seconds = r.remaining_seconds();
                LeaseInfo {
                    lease_id: r.id.to_string(),
                    target_type: r.target_type,
                    state: r.state.as_str().to_string(),
                    remaining_seconds,
                    renewable: r.renewable,
                }
            })
            .collect();

        Ok(Response::new(ListLeasesResponse { leases }))
    }
}

/// Create a sample lease record for seeding/testing purposes.
///
/// Not called in production paths — only used in integration tests that need
/// a pre-populated store.
#[allow(dead_code)]
pub async fn seed_lease(
    store: &Arc<dyn LeaseStoreBackend>,
    tenant_id: impl Into<String>,
    target_type: impl Into<String>,
    ttl_seconds: i64,
    max_ttl_seconds: i64,
    renewable: bool,
) -> LeaseId {
    use chrono::Duration;

    let id = LeaseId::new();
    let now = chrono::Utc::now();
    let record = LeaseRecord {
        id: id.clone(),
        tenant_id: tenant_id.into(),
        target_type: target_type.into(),
        target_data: "{}".to_string(),
        state: LeaseState::Active,
        ttl_seconds,
        max_ttl_seconds,
        renewable,
        issued_at: now,
        expires_at: now + Duration::seconds(ttl_seconds),
        revoked_at: None,
    };

    store.insert_lease(record).await;
    id
}
