//! gRPC service implementation for the lease-manager.
//!
//! Implements the `LeaseService` trait generated by tonic from the
//! `wslvault.lease.v1` proto package. Each handler delegates storage
//! mutations to the injected `LeaseStoreBackend` and returns proto-typed
//! responses.

use std::sync::Arc;

use tonic::{Request, Response, Status};
use uuid::Uuid;

use crate::store::{LeaseId, LeaseRecord, LeaseState, LeaseStoreBackend};

use proto::lease_service_server::LeaseService;
use proto::{
    CreateLeaseRequest, CreateLeaseResponse, GetLeaseRequest, GetLeaseResponse, LeaseInfo,
    ListLeasesRequest, ListLeasesResponse, RenewLeaseRequest, RenewLeaseResponse,
    RevokeLeaseRequest, RevokeLeaseResponse,
};

pub mod proto {
    tonic::include_proto!("wslvault.lease.v1");
}

/// Concrete gRPC service handler.
#[derive(Clone)]
pub struct LeaseServiceImpl {
    store: Arc<dyn LeaseStoreBackend>,
}

impl LeaseServiceImpl {
    pub fn new(store: Arc<dyn LeaseStoreBackend>) -> Self {
        Self { store }
    }
}

#[tonic::async_trait]
impl LeaseService for LeaseServiceImpl {
    async fn create_lease(
        &self,
        request: Request<CreateLeaseRequest>,
    ) -> Result<Response<CreateLeaseResponse>, Status> {
        let req = request.into_inner();

        if req.tenant_id.is_empty() {
            return Err(Status::invalid_argument("tenant_id is required"));
        }
        if Uuid::parse_str(&req.tenant_id).is_err() {
            return Err(Status::invalid_argument("tenant_id must be a UUID"));
        }
        if req.ttl_seconds <= 0 {
            return Err(Status::invalid_argument("ttl_seconds must be positive"));
        }

        let mut ttl = req.ttl_seconds;
        let mut max_ttl = req.max_ttl_seconds;
        if max_ttl <= 0 {
            max_ttl = 86_400;
        }
        if ttl > max_ttl {
            ttl = max_ttl;
        }

        let target: wslvault_core::types::lease::LeaseTarget =
            serde_json::from_str(&req.target_data).map_err(|e| {
                Status::invalid_argument(format!("target_data is not valid LeaseTarget JSON: {e}"))
            })?;

        let expected_type = match &target {
            wslvault_core::types::lease::LeaseTarget::Token { .. } => "token",
            wslvault_core::types::lease::LeaseTarget::DynamicSecret { .. } => "dynamic_secret",
            wslvault_core::types::lease::LeaseTarget::ServiceCredential { .. } => {
                "service_credential"
            }
        };
        if !req.target_type.is_empty() && req.target_type != expected_type {
            return Err(Status::invalid_argument(format!(
                "target_type '{}' does not match target_data ({expected_type})",
                req.target_type
            )));
        }

        let target_type = expected_type.to_string();
        let target_data = serde_json::to_string(&target)
            .map_err(|e| Status::internal(format!("failed to serialise lease target: {e}")))?;

        let now = chrono::Utc::now();
        let id = LeaseId::new();
        let record = LeaseRecord {
            id: id.clone(),
            tenant_id: req.tenant_id,
            target_type,
            target_data,
            state: LeaseState::Active,
            ttl_seconds: ttl,
            max_ttl_seconds: max_ttl,
            renewable: req.renewable,
            issued_at: now,
            expires_at: now + chrono::Duration::seconds(ttl),
            revoked_at: None,
        };
        let expires_at = record.expires_at.to_rfc3339();

        self.store
            .insert_lease(record)
            .await
            .map_err(Status::internal)?;

        Ok(Response::new(CreateLeaseResponse {
            lease_id: id.to_string(),
            ttl_seconds: ttl,
            expires_at,
            renewable: req.renewable,
        }))
    }

    /// Return the full lease record for the given lease ID.
    async fn get_lease(
        &self,
        request: Request<GetLeaseRequest>,
    ) -> Result<Response<GetLeaseResponse>, Status> {
        let req = request.into_inner();
        let lease_id = req
            .lease_id
            .parse::<LeaseId>()
            .map_err(|_| Status::invalid_argument("invalid lease_id format"))?;

        let record = self
            .store
            .get_lease(&lease_id)
            .await
            .ok_or_else(|| Status::not_found(format!("lease not found: {}", lease_id)))?;

        // Compute derived fields before consuming the record by field-moving.
        let remaining_seconds = record.remaining_seconds();
        let response = GetLeaseResponse {
            lease_id: record.id.to_string(),
            tenant_id: record.tenant_id,
            target_type: record.target_type,
            state: record.state.as_str().to_string(),
            ttl_seconds: record.ttl_seconds,
            remaining_seconds,
            renewable: record.renewable,
            issued_at: record.issued_at.to_rfc3339(),
            expires_at: record.expires_at.to_rfc3339(),
        };

        Ok(Response::new(response))
    }

    /// Extend the expiry of an active, renewable lease.
    async fn renew_lease(
        &self,
        request: Request<RenewLeaseRequest>,
    ) -> Result<Response<RenewLeaseResponse>, Status> {
        let req = request.into_inner();
        let lease_id = req
            .lease_id
            .parse::<LeaseId>()
            .map_err(|_| Status::invalid_argument("invalid lease_id format"))?;

        if req.increment_seconds <= 0 {
            return Err(Status::invalid_argument(
                "increment_seconds must be positive",
            ));
        }

        let updated = self
            .store
            .renew_lease(&lease_id, req.increment_seconds)
            .await
            .map_err(Status::failed_precondition)?;

        let response = RenewLeaseResponse {
            lease_id: updated.id.to_string(),
            ttl_seconds: updated.ttl_seconds,
            expires_at: updated.expires_at.to_rfc3339(),
        };

        Ok(Response::new(response))
    }

    /// Immediately revoke a lease, transitioning it to the Revoked state.
    async fn revoke_lease(
        &self,
        request: Request<RevokeLeaseRequest>,
    ) -> Result<Response<RevokeLeaseResponse>, Status> {
        let req = request.into_inner();
        let lease_id = req
            .lease_id
            .parse::<LeaseId>()
            .map_err(|_| Status::invalid_argument("invalid lease_id format"))?;

        self.store
            .revoke_lease(&lease_id)
            .await
            .map_err(Status::not_found)?;

        Ok(Response::new(RevokeLeaseResponse {}))
    }

    /// List all leases for a tenant with an optional state filter.
    async fn list_leases(
        &self,
        request: Request<ListLeasesRequest>,
    ) -> Result<Response<ListLeasesResponse>, Status> {
        let req = request.into_inner();

        if req.tenant_id.is_empty() {
            return Err(Status::invalid_argument("tenant_id is required"));
        }

        let state_filter = if req.state_filter.is_empty() {
            None
        } else {
            Some(req.state_filter.as_str())
        };

        let records = self.store.list_leases(&req.tenant_id, state_filter).await;

        let leases: Vec<LeaseInfo> = records
            .into_iter()
            .map(|r| {
                // Compute remaining_seconds before field-moves consume the record.
                let remaining_seconds = r.remaining_seconds();
                LeaseInfo {
                    lease_id: r.id.to_string(),
                    target_type: r.target_type,
                    state: r.state.as_str().to_string(),
                    remaining_seconds,
                    renewable: r.renewable,
                }
            })
            .collect();

        Ok(Response::new(ListLeasesResponse { leases }))
    }
}

/// Create a sample lease record for seeding/testing purposes.
///
/// Not called in production paths — only used in integration tests that need
/// a pre-populated store.
#[allow(dead_code)]
pub async fn seed_lease(
    store: &Arc<dyn LeaseStoreBackend>,
    tenant_id: impl Into<String>,
    target_type: impl Into<String>,
    ttl_seconds: i64,
    max_ttl_seconds: i64,
    renewable: bool,
) -> LeaseId {
    use chrono::Duration;

    let id = LeaseId::new();
    let now = chrono::Utc::now();
    let record = LeaseRecord {
        id: id.clone(),
        tenant_id: tenant_id.into(),
        target_type: target_type.into(),
        target_data: "{}".to_string(),
        state: LeaseState::Active,
        ttl_seconds,
        max_ttl_seconds,
        renewable,
        issued_at: now,
        expires_at: now + Duration::seconds(ttl_seconds),
        revoked_at: None,
    };

    store
        .insert_lease(record)
        .await
        .expect("seed insert must succeed");
    id
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::store::InMemoryLeaseStore;
    use proto::lease_service_server::LeaseService;

    fn token_target(hash: &str, principal: &str) -> String {
        serde_json::to_string(&wslvault_core::types::lease::LeaseTarget::Token {
            token_id: hash.into(),
            principal_id: principal.into(),
        })
        .unwrap()
    }

    async fn svc() -> LeaseServiceImpl {
        LeaseServiceImpl::new(Arc::new(InMemoryLeaseStore::new()))
    }

    #[tokio::test]
    async fn create_get_list_renew_revoke() {
        let svc = svc().await;
        let tenant = uuid::Uuid::now_v7().to_string();

        let created = svc
            .create_lease(Request::new(CreateLeaseRequest {
                tenant_id: tenant.clone(),
                target_type: "token".into(),
                target_data: token_target(&"a".repeat(64), "principal-1"),
                ttl_seconds: 3600,
                max_ttl_seconds: 86_400,
                renewable: true,
            }))
            .await
            .unwrap()
            .into_inner();

        assert!(!created.lease_id.is_empty());
        assert_eq!(created.ttl_seconds, 3600);

        let got = svc
            .get_lease(Request::new(GetLeaseRequest {
                lease_id: created.lease_id.clone(),
            }))
            .await
            .unwrap()
            .into_inner();
        assert_eq!(got.tenant_id, tenant);
        assert_eq!(got.target_type, "token");

        let listed = svc
            .list_leases(Request::new(ListLeasesRequest {
                tenant_id: tenant.clone(),
                state_filter: "active".into(),
            }))
            .await
            .unwrap()
            .into_inner();
        assert_eq!(listed.leases.len(), 1);
        assert_eq!(listed.leases[0].lease_id, created.lease_id);

        let renewed = svc
            .renew_lease(Request::new(RenewLeaseRequest {
                lease_id: created.lease_id.clone(),
                increment_seconds: 1800,
            }))
            .await
            .unwrap()
            .into_inner();
        assert_eq!(renewed.lease_id, created.lease_id);

        svc.revoke_lease(Request::new(RevokeLeaseRequest {
            lease_id: created.lease_id.clone(),
        }))
        .await
        .unwrap();

        let after = svc
            .get_lease(Request::new(GetLeaseRequest {
                lease_id: created.lease_id,
            }))
            .await
            .unwrap()
            .into_inner();
        assert_eq!(after.state, "revoked");
    }

    #[tokio::test]
    async fn create_caps_ttl_to_max_and_rejects_non_positive() {
        let svc = svc().await;
        let tenant = uuid::Uuid::now_v7().to_string();

        let err = svc
            .create_lease(Request::new(CreateLeaseRequest {
                tenant_id: tenant.clone(),
                target_type: "token".into(),
                target_data: token_target(&"b".repeat(64), ""),
                ttl_seconds: 0,
                max_ttl_seconds: 3600,
                renewable: true,
            }))
            .await
            .unwrap_err();
        assert_eq!(err.code(), tonic::Code::InvalidArgument);

        let created = svc
            .create_lease(Request::new(CreateLeaseRequest {
                tenant_id: tenant,
                target_type: "token".into(),
                target_data: token_target(&"c".repeat(64), ""),
                ttl_seconds: 10_000,
                max_ttl_seconds: 3600,
                renewable: true,
            }))
            .await
            .unwrap()
            .into_inner();
        assert_eq!(created.ttl_seconds, 3600);
    }

    #[tokio::test]
    async fn revoke_missing_is_not_found() {
        let svc = svc().await;
        let err = svc
            .revoke_lease(Request::new(RevokeLeaseRequest {
                lease_id: uuid::Uuid::now_v7().to_string(),
            }))
            .await
            .unwrap_err();
        assert_eq!(err.code(), tonic::Code::NotFound);
    }
}
