//! gRPC service implementation for the identity-service.
//!
//! Implements the `IdentityService` trait generated by `tonic` from the proto
//! definition.  All business logic is delegated to `TokenManager` and
//! `PrincipalStore`; this module is responsible only for protocol translation
//! and RPC error mapping.

use std::{
    collections::HashSet,
    sync::{Arc, RwLock},
};

use chrono::Utc;
use tonic::{Request, Response, Status};
use tracing::{error, info, warn};
use uuid::Uuid;
use wslvault_core::{types::principal::AuthMethod, VaultError};

use crate::{
    aws_iam::AwsIamManager,
    azure_workload::AzureWorkloadManager,
    mtls::MtlsManager,
    oidc::OidcManager,
    // `include_proto!("wslvault.identity.v1")` inlines the generated file at
    // this module level — there are no nested sub-modules for the package path.
    proto::{
        authenticate_request::Method, identity_service_server::IdentityService,
        AuthenticateRequest, AuthenticateResponse, CreateServiceAccountRequest,
        CreateServiceAccountResponse, ListServiceAccountsRequest, ListServiceAccountsResponse,
        RevokeTokenByHashRequest, RevokeTokenByHashResponse, RevokeTokenRequest,
        RevokeTokenResponse, ServiceAccountInfo, ValidateTokenRequest, ValidateTokenResponse,
    },
    store::{PrincipalRecord, PrincipalStore},
    token::TokenManager,
};

/// Default TTL used when a caller does not supply one for service accounts.
const DEFAULT_TTL_SECONDS: i64 = 3600;

/// Default TTL used when re-issuing a token after token-based authentication.
const TOKEN_REISSUE_TTL_SECONDS: i64 = 3600;

/// Maps a `VaultError` to the closest gRPC `Status`.
fn vault_err_to_status(err: VaultError) -> Status {
    match &err {
        VaultError::Unauthenticated { reason } => Status::unauthenticated(reason.clone()),
        VaultError::PermissionDenied { reason, .. } => Status::permission_denied(reason.clone()),
        VaultError::TenantNotFound { tenant_id } => {
            Status::not_found(format!("not found: {tenant_id}"))
        }
        VaultError::ValidationError { field, reason } => {
            Status::invalid_argument(format!("{field}: {reason}"))
        }
        other => {
            error!(error = %other, "internal identity-service error");
            Status::internal(other.to_string())
        }
    }
}

/// Concrete implementation of the gRPC `IdentityService`.
pub struct IdentityServiceImpl {
    token_manager: TokenManager,
    store: PrincipalStore,
    /// Durable revocation list. `Some` whenever `DATABASE_URL` is configured.
    ///
    /// Revocations used to be an in-process `HashSet<String>` of raw tokens,
    /// which meant revoking on one replica left the token live on the other,
    /// a restart un-revoked everything, and the set grew without bound. It is
    /// now a Postgres table keyed by SHA-256 of the token.
    revocation_pool: Option<wslvault_storage::pool::DbPool>,
    /// Fallback used only when no database is configured (local dev). Retained
    /// so single-process development still behaves, but it carries all the
    /// original caveats and the service warns about it at startup.
    revoked_tokens: Arc<RwLock<HashSet<String>>>,
    /// Optional OIDC manager.  Present only when `VAULT_OIDC_PROVIDERS` is
    /// configured at startup; `None` causes OIDC auth attempts to return
    /// `Status::unavailable`.
    oidc_manager: Option<Arc<OidcManager>>,
    /// Optional mTLS manager.  Present only when `VAULT_MTLS_ENABLED=true` is
    /// set at startup; `None` causes mTLS auth attempts to return
    /// `Status::unavailable`.
    mtls_manager: Option<Arc<MtlsManager>>,
    /// Optional AWS IAM auth manager.
    aws_iam_manager: Option<Arc<AwsIamManager>>,
    /// Optional Azure Workload Identity manager.
    azure_workload_manager: Option<Arc<AzureWorkloadManager>>,
}

impl IdentityServiceImpl {
    pub fn new(
        token_manager: TokenManager,
        store: PrincipalStore,
        oidc_manager: Option<Arc<OidcManager>>,
        mtls_manager: Option<Arc<MtlsManager>>,
        aws_iam_manager: Option<Arc<AwsIamManager>>,
        azure_workload_manager: Option<Arc<AzureWorkloadManager>>,
        revocation_pool: Option<wslvault_storage::pool::DbPool>,
    ) -> Self {
        if revocation_pool.is_none() {
            warn!(
                "token revocation: DATABASE_URL not set, falling back to an in-process set. \
                 Revocations will NOT survive a restart and will NOT reach other replicas."
            );
        }
        Self {
            token_manager,
            store,
            revocation_pool,
            revoked_tokens: Arc::new(RwLock::new(HashSet::new())),
            oidc_manager,
            mtls_manager,
            aws_iam_manager,
            azure_workload_manager,
        }
    }

    /// Whether the token has been explicitly revoked before its natural expiry.
    ///
    /// **Fails closed.** If the revocation list cannot be consulted — the
    /// database is unreachable, or the in-memory lock is poisoned — this
    /// reports the token as revoked. The previous implementation did the
    /// opposite and treated an unreadable list as "not revoked", so the one
    /// moment revocation mattered most was the moment it stopped working.
    async fn is_revoked(&self, token: &str) -> bool {
        if let Some(pool) = &self.revocation_pool {
            return match wslvault_storage::revocation_store::is_revoked(pool, token).await {
                Ok(revoked) => revoked,
                Err(e) => {
                    error!(error = %e, "revocation lookup failed — denying (fail-closed)");
                    true
                }
            };
        }

        match self.revoked_tokens.read() {
            Ok(set) => set.contains(&wslvault_storage::revocation_store::token_hash(token)),
            Err(e) => {
                error!(error = %e, "revocation set lock poisoned — denying (fail-closed)");
                true
            }
        }
    }
}

#[tonic::async_trait]
impl IdentityService for IdentityServiceImpl {
    /// Authenticates a caller using the supplied method and issues a new JWT.
    ///
    /// Supported methods:
    /// - `TokenAuth`: validates an existing token and re-issues a fresh one.
    /// - `OidcAuth`: stub — not yet integrated with an OIDC provider.
    /// - `MtlsAuth`: validates a PEM-encoded X.509 client certificate against
    ///   the configured trusted CA and issues a token for the cert principal.
    async fn authenticate(
        &self,
        request: Request<AuthenticateRequest>,
    ) -> Result<Response<AuthenticateResponse>, Status> {
        let req = request.into_inner();

        if req.tenant_id.is_empty() {
            return Err(Status::invalid_argument("tenant_id must not be empty"));
        }

        let method = req.method.ok_or_else(|| {
            Status::invalid_argument("authenticate request must include an auth method")
        })?;

        // Resolve (principal_id, policies) from the supplied auth method.
        let (principal_id, policies): (String, Vec<String>) = match method {
            Method::Token(token_auth) => {
                if self.is_revoked(&token_auth.token).await {
                    return Err(Status::unauthenticated("token has been revoked"));
                }

                let claims = self
                    .token_manager
                    .validate_token(&token_auth.token)
                    .map_err(vault_err_to_status)?;

                // Confirm the token belongs to the requested tenant.
                if claims.tenant_id != req.tenant_id {
                    warn!(
                        principal_id = %claims.sub,
                        token_tenant = %claims.tenant_id,
                        request_tenant = %req.tenant_id,
                        "tenant mismatch during token authentication"
                    );
                    return Err(Status::permission_denied(
                        "token does not belong to the requested tenant",
                    ));
                }

                (claims.sub, claims.policies)
            }
            Method::Oidc(oidc_auth) => {
                // Require that an OIDC manager is configured; return a clear
                // error if the operator has not set VAULT_OIDC_PROVIDERS.
                let manager = self
                    .oidc_manager
                    .as_ref()
                    .ok_or_else(|| Status::unavailable("OIDC authentication is not configured"))?;

                // Validate the caller-supplied ID token against the named
                // provider and extract the wslvault principal concepts.
                let result = manager
                    .validate_id_token(&oidc_auth.provider, &oidc_auth.id_token)
                    .await
                    .map_err(|e| Status::unauthenticated(format!("OIDC validation failed: {e}")))?;

                // Confirm the OIDC-derived tenant matches the requested tenant
                // to prevent cross-tenant token injection attacks.
                if result.tenant_id != req.tenant_id {
                    warn!(
                        provider = %oidc_auth.provider,
                        oidc_tenant = %result.tenant_id,
                        request_tenant = %req.tenant_id,
                        "OIDC tenant claim does not match requested tenant"
                    );
                    return Err(Status::permission_denied(
                        "OIDC tenant claim does not match the requested tenant",
                    ));
                }

                // Construct a stable, provider-scoped principal ID so the same
                // OIDC user always maps to the same wslvault principal across
                // logins.
                let principal_id = format!("oidc:{}:{}", oidc_auth.provider, result.subject);

                // Upsert the principal record — create on first login, silently
                // ignore the duplicate-key error on subsequent logins so the
                // principal is always registered before a token is issued.
                let record = PrincipalRecord {
                    id: principal_id.clone(),
                    tenant_id: result.tenant_id.clone(),
                    display_name: result.display_name.clone(),
                    auth_method: AuthMethod::Token,
                    policies: result.policies.clone(),
                    created_at: Utc::now(),
                };

                match self.store.create_principal(record) {
                    Ok(()) => {}
                    // A ValidationError means the principal was already
                    // registered on a prior login; that is expected.
                    Err(VaultError::ValidationError { .. }) => {}
                    Err(other) => return Err(vault_err_to_status(other)),
                }

                (principal_id, result.policies)
            }
            Method::AwsIam(aws_auth) => {
                let manager = self.aws_iam_manager.as_ref().ok_or_else(|| {
                    Status::unavailable("AWS IAM authentication is not configured")
                })?;

                let result = manager
                    .validate(
                        &aws_auth.iam_request_url,
                        &aws_auth.iam_request_body,
                        &aws_auth.iam_request_headers,
                        &aws_auth.bound_iam_role_arn,
                        &req.tenant_id,
                    )
                    .await
                    .map_err(|e| {
                        Status::unauthenticated(format!("AWS IAM validation failed: {e}"))
                    })?;

                // Cross-check tenant.
                if result.tenant_id != req.tenant_id {
                    warn!(
                        arn = %result.arn,
                        resolved_tenant = %result.tenant_id,
                        request_tenant = %req.tenant_id,
                        "AWS IAM tenant does not match requested tenant"
                    );
                    return Err(Status::permission_denied(
                        "AWS account does not map to the requested tenant",
                    ));
                }

                let principal_id = format!("aws:{}", result.arn);

                // Upsert the principal record.
                let record = PrincipalRecord {
                    id: principal_id.clone(),
                    tenant_id: result.tenant_id.clone(),
                    display_name: result.display_name.clone(),
                    auth_method: AuthMethod::AwsIam {
                        account_id: result.account_id.clone(),
                        arn: result.arn.clone(),
                    },
                    policies: result.policies.clone(),
                    created_at: Utc::now(),
                };

                match self.store.create_principal(record) {
                    Ok(()) => {}
                    Err(VaultError::ValidationError { .. }) => {}
                    Err(other) => return Err(vault_err_to_status(other)),
                }

                info!(
                    principal_id = %principal_id,
                    arn = %result.arn,
                    account_id = %result.account_id,
                    "AWS IAM principal authenticated"
                );

                (principal_id, result.policies)
            }
            Method::AzureWorkload(azure_auth) => {
                let manager = self.azure_workload_manager.as_ref().ok_or_else(|| {
                    Status::unavailable("Azure Workload Identity authentication is not configured")
                })?;

                let result = manager
                    .validate(
                        &azure_auth.jwt,
                        &azure_auth.azure_tenant_id,
                        &azure_auth.subscription_id,
                        &req.tenant_id,
                    )
                    .await
                    .map_err(|e| {
                        Status::unauthenticated(format!(
                            "Azure Workload Identity validation failed: {e}"
                        ))
                    })?;

                // Cross-check tenant.
                if result.tenant_id != req.tenant_id {
                    warn!(
                        object_id = %result.object_id,
                        resolved_tenant = %result.tenant_id,
                        request_tenant = %req.tenant_id,
                        "Azure tenant does not match requested tenant"
                    );
                    return Err(Status::permission_denied(
                        "Azure AD tenant does not map to the requested tenant",
                    ));
                }

                let principal_id = format!("azure:{}", result.object_id);

                // Upsert the principal record.
                let record = PrincipalRecord {
                    id: principal_id.clone(),
                    tenant_id: result.tenant_id.clone(),
                    display_name: result.display_name.clone(),
                    auth_method: AuthMethod::AzureWorkload {
                        object_id: result.object_id.clone(),
                        azure_tenant_id: result.azure_tenant_id.clone(),
                    },
                    policies: result.policies.clone(),
                    created_at: Utc::now(),
                };

                match self.store.create_principal(record) {
                    Ok(()) => {}
                    Err(VaultError::ValidationError { .. }) => {}
                    Err(other) => return Err(vault_err_to_status(other)),
                }

                info!(
                    principal_id = %principal_id,
                    object_id = %result.object_id,
                    azure_tenant = %result.azure_tenant_id,
                    "Azure Workload Identity principal authenticated"
                );

                (principal_id, result.policies)
            }
            Method::Mtls(mtls_auth) => {
                // Require that the mTLS manager was configured at startup.
                let manager = self
                    .mtls_manager
                    .as_ref()
                    .ok_or_else(|| Status::unavailable("mTLS authentication is not configured"))?;

                let result = manager
                    .validate_certificate(&mtls_auth.certificate_pem)
                    .map_err(|e| Status::unauthenticated(format!("mTLS validation failed: {e}")))?;

                // Prefix the principal id so it is distinguishable from other
                // auth methods in audit logs and policy evaluation.
                let mtls_principal_id = format!("mtls:{}", result.principal_id);

                // Verify that the tenant encoded in the certificate matches
                // the tenant_id supplied in the request, consistent with the
                // cross-check done for token-based authentication.
                if result.tenant_id != req.tenant_id {
                    warn!(
                        principal_id = %mtls_principal_id,
                        cert_tenant = %result.tenant_id,
                        request_tenant = %req.tenant_id,
                        "tenant mismatch during mTLS authentication"
                    );
                    return Err(Status::permission_denied(
                        "certificate tenant does not match the requested tenant",
                    ));
                }

                let (token, expires_at) = self
                    .token_manager
                    .issue_token(
                        &mtls_principal_id,
                        &result.tenant_id,
                        result.policies.clone(),
                        TOKEN_REISSUE_TTL_SECONDS,
                    )
                    .map_err(vault_err_to_status)?;

                let lease_id = crate::lease_client::try_create_token_lease(
                    &result.tenant_id,
                    &mtls_principal_id,
                    &token,
                    TOKEN_REISSUE_TTL_SECONDS,
                )
                .await
                .unwrap_or_default();

                info!(
                    principal_id = %mtls_principal_id,
                    tenant_id = %result.tenant_id,
                    serial = %result.serial_number,
                    display_name = %result.display_name,
                    expires_at = %expires_at,
                    "mTLS principal authenticated; token issued"
                );

                return Ok(Response::new(AuthenticateResponse {
                    token,
                    principal_id: mtls_principal_id,
                    tenant_id: result.tenant_id,
                    policies: result.policies,
                    expires_at: expires_at.timestamp(),
                    lease_id,
                }));
            }
        };

        let (new_token, expires_at) = self
            .token_manager
            .issue_token(
                &principal_id,
                &req.tenant_id,
                policies.clone(),
                TOKEN_REISSUE_TTL_SECONDS,
            )
            .map_err(vault_err_to_status)?;

        let lease_id = crate::lease_client::try_create_token_lease(
            &req.tenant_id,
            &principal_id,
            &new_token,
            TOKEN_REISSUE_TTL_SECONDS,
        )
        .await
        .unwrap_or_default();

        info!(
            principal_id = %principal_id,
            tenant_id = %req.tenant_id,
            expires_at = %expires_at,
            "principal authenticated; new token issued"
        );

        Ok(Response::new(AuthenticateResponse {
            token: new_token,
            principal_id,
            tenant_id: req.tenant_id,
            policies,
            expires_at: expires_at.timestamp(),
            lease_id,
        }))
    }

    /// Validates a JWT and returns the embedded principal information.
    ///
    /// Also checks the in-memory revocation set so that explicitly revoked
    /// tokens are rejected even before their natural expiry.
    async fn validate_token(
        &self,
        request: Request<ValidateTokenRequest>,
    ) -> Result<Response<ValidateTokenResponse>, Status> {
        let req = request.into_inner();

        if req.token.is_empty() {
            return Ok(Response::new(ValidateTokenResponse {
                valid: false,
                principal_id: String::new(),
                tenant_id: String::new(),
                policies: vec![],
            }));
        }

        // A revoked token is invalid regardless of its cryptographic validity.
        if self.is_revoked(&req.token).await {
            return Ok(Response::new(ValidateTokenResponse {
                valid: false,
                principal_id: String::new(),
                tenant_id: String::new(),
                policies: vec![],
            }));
        }

        match self.token_manager.validate_token(&req.token) {
            Ok(claims) => Ok(Response::new(ValidateTokenResponse {
                valid: true,
                principal_id: claims.sub,
                tenant_id: claims.tenant_id,
                policies: claims.policies,
            })),
            Err(VaultError::Unauthenticated { .. }) => Ok(Response::new(ValidateTokenResponse {
                valid: false,
                principal_id: String::new(),
                tenant_id: String::new(),
                policies: vec![],
            })),
            Err(other) => Err(vault_err_to_status(other)),
        }
    }

    /// Revoke a token before its natural expiry.
    ///
    /// Persisted to `system.revoked_tokens` when a database is configured, so
    /// the revocation survives restarts and is seen by every replica. Only the
    /// SHA-256 of the token is stored, never the token itself.
    ///
    /// The token's own `exp` claim bounds how long the record is kept: past
    /// that instant the JWT validator rejects it anyway, so the row is reaped.
    /// A token that cannot be decoded is still revoked — it is retained for a
    /// nominal hour so a malformed-but-live credential cannot be laundered by
    /// mangling it.
    async fn revoke_token(
        &self,
        request: Request<RevokeTokenRequest>,
    ) -> Result<Response<RevokeTokenResponse>, Status> {
        let req = request.into_inner();

        if req.token.is_empty() {
            return Err(Status::invalid_argument("token must not be empty"));
        }

        // Decode without verifying: we want the exp/sub/tenant of a token we
        // are about to reject, and refusing to revoke an already-expired or
        // otherwise unverifiable token would be the wrong way round.
        let (tenant_id, principal_id, expires_at) =
            match self.token_manager.validate_token(&req.token) {
                Ok(c) => (c.tenant_id, c.sub, c.exp),
                Err(_) => (
                    String::new(),
                    String::new(),
                    chrono::Utc::now().timestamp() + 3600,
                ),
            };

        if let Some(pool) = &self.revocation_pool {
            wslvault_storage::revocation_store::revoke(
                pool,
                &req.token,
                &tenant_id,
                &principal_id,
                expires_at,
            )
            .await
            .map_err(|e| {
                // Report the failure rather than swallowing it. A caller that
                // believes a token is revoked when it is not is worse off than
                // one that knows the revocation did not land and can retry.
                error!(error = %e, "failed to persist token revocation");
                Status::internal("could not persist revocation")
            })?;
        } else {
            let mut set = self.revoked_tokens.write().map_err(|e| {
                error!(error = %e, "revocation set lock poisoned");
                Status::internal("internal lock error")
            })?;
            set.insert(wslvault_storage::revocation_store::token_hash(&req.token));
        }

        info!(
            tenant_id = %tenant_id,
            principal_id = %principal_id,
            durable = self.revocation_pool.is_some(),
            "token revoked"
        );

        Ok(Response::new(RevokeTokenResponse {}))
    }

    async fn revoke_token_by_hash(
        &self,
        request: Request<RevokeTokenByHashRequest>,
    ) -> Result<Response<RevokeTokenByHashResponse>, Status> {
        let req = request.into_inner();

        if req.token_hash.len() != 64 || !req.token_hash.chars().all(|c| c.is_ascii_hexdigit()) {
            return Err(Status::invalid_argument(
                "token_hash must be 64 hex characters",
            ));
        }

        let expires_at = if req.expires_at > 0 {
            req.expires_at
        } else {
            chrono::Utc::now().timestamp() + 3600
        };

        if let Some(pool) = &self.revocation_pool {
            wslvault_storage::revocation_store::revoke_by_hash(
                pool,
                &req.token_hash,
                &req.tenant_id,
                &req.principal_id,
                expires_at,
            )
            .await
            .map_err(|e| {
                error!(error = %e, "failed to persist token revocation by hash");
                Status::internal("could not persist revocation")
            })?;
        } else {
            let mut set = self.revoked_tokens.write().map_err(|e| {
                error!(error = %e, "revocation set lock poisoned");
                Status::internal("internal lock error")
            })?;
            set.insert(req.token_hash.clone());
        }

        info!(
            tenant_id = %req.tenant_id,
            principal_id = %req.principal_id,
            durable = self.revocation_pool.is_some(),
            "token revoked by hash"
        );

        Ok(Response::new(RevokeTokenByHashResponse {}))
    }

    /// Creates a new service-account principal and issues an initial JWT.
    ///
    /// A service account is a machine identity with a stable principal_id and
    /// a set of policies.  The caller receives the principal_id, the initial
    /// token, and a lease_id for lease-tracking purposes.
    async fn create_service_account(
        &self,
        request: Request<CreateServiceAccountRequest>,
    ) -> Result<Response<CreateServiceAccountResponse>, Status> {
        let req = request.into_inner();

        if req.tenant_id.is_empty() {
            return Err(Status::invalid_argument("tenant_id must not be empty"));
        }
        if req.name.is_empty() {
            return Err(Status::invalid_argument("name must not be empty"));
        }

        let principal_id = Uuid::now_v7().to_string();
        let ttl_seconds = if req.ttl_seconds > 0 {
            req.ttl_seconds
        } else {
            DEFAULT_TTL_SECONDS
        };

        let record = PrincipalRecord {
            id: principal_id.clone(),
            tenant_id: req.tenant_id.clone(),
            display_name: req.name.clone(),
            auth_method: AuthMethod::MachineIdentity {
                service_account: req.name.clone(),
            },
            policies: req.policies.clone(),
            created_at: Utc::now(),
        };

        self.store
            .create_principal(record)
            .map_err(vault_err_to_status)?;

        let (token, _expires_at) = self
            .token_manager
            .issue_token(&principal_id, &req.tenant_id, req.policies, ttl_seconds)
            .map_err(vault_err_to_status)?;

        let lease_id = crate::lease_client::try_create_token_lease(
            &req.tenant_id,
            &principal_id,
            &token,
            ttl_seconds,
        )
        .await
        .unwrap_or_default();

        info!(
            principal_id = %principal_id,
            tenant_id = %req.tenant_id,
            name = %req.name,
            "service account created"
        );

        Ok(Response::new(CreateServiceAccountResponse {
            principal_id,
            token,
            lease_id,
        }))
    }

    /// Lists all service accounts (principals) registered for a tenant.
    async fn list_service_accounts(
        &self,
        request: Request<ListServiceAccountsRequest>,
    ) -> Result<Response<ListServiceAccountsResponse>, Status> {
        let req = request.into_inner();

        if req.tenant_id.is_empty() {
            return Err(Status::invalid_argument("tenant_id must not be empty"));
        }

        let records = self
            .store
            .list_principals(&req.tenant_id)
            .map_err(vault_err_to_status)?;

        let accounts: Vec<ServiceAccountInfo> = records
            .into_iter()
            .map(|r| ServiceAccountInfo {
                principal_id: r.id,
                name: r.display_name,
                policies: r.policies,
                // RFC 3339 string expected by the proto definition.
                created_at: r.created_at.to_rfc3339(),
            })
            .collect();

        Ok(Response::new(ListServiceAccountsResponse { accounts }))
    }
}
