//! gRPC service implementation for the identity-service.
//!
//! Implements the `IdentityService` trait generated by `tonic` from the proto
//! definition.  All business logic is delegated to `TokenManager` and
//! `PrincipalStore`; this module is responsible only for protocol translation
//! and RPC error mapping.

use std::{
    collections::HashSet,
    sync::{Arc, RwLock},
};

use chrono::Utc;
use tonic::{Request, Response, Status};
use tracing::{error, info, warn};
use uuid::Uuid;
use wslvault_core::{types::principal::AuthMethod, VaultError};

use crate::{
    aws_iam::AwsIamManager,
    azure_workload::AzureWorkloadManager,
    mtls::MtlsManager,
    oidc::OidcManager,
    // `include_proto!("wslvault.identity.v1")` inlines the generated file at
    // this module level — there are no nested sub-modules for the package path.
    proto::{
        authenticate_request::Method, identity_service_server::IdentityService,
        AuthenticateRequest, AuthenticateResponse, CreateServiceAccountRequest,
        CreateServiceAccountResponse, ListServiceAccountsRequest, ListServiceAccountsResponse,
        RevokeTokenRequest, RevokeTokenResponse, ServiceAccountInfo, ValidateTokenRequest,
        ValidateTokenResponse,
    },
    store::{PrincipalRecord, PrincipalStore},
    token::TokenManager,
};

/// Default TTL used when a caller does not supply one for service accounts.
const DEFAULT_TTL_SECONDS: i64 = 3600;

/// Default TTL used when re-issuing a token after token-based authentication.
const TOKEN_REISSUE_TTL_SECONDS: i64 = 3600;

/// Maps a `VaultError` to the closest gRPC `Status`.
fn vault_err_to_status(err: VaultError) -> Status {
    match &err {
        VaultError::Unauthenticated { reason } => Status::unauthenticated(reason.clone()),
        VaultError::PermissionDenied { reason, .. } => Status::permission_denied(reason.clone()),
        VaultError::TenantNotFound { tenant_id } => {
            Status::not_found(format!("not found: {tenant_id}"))
        }
        VaultError::ValidationError { field, reason } => {
            Status::invalid_argument(format!("{field}: {reason}"))
        }
        other => {
            error!(error = %other, "internal identity-service error");
            Status::internal(other.to_string())
        }
    }
}

/// Concrete implementation of the gRPC `IdentityService`.
pub struct IdentityServiceImpl {
    token_manager: TokenManager,
    store: PrincipalStore,
    /// In-memory revocation set: stores raw token strings that have been
    /// explicitly revoked before their natural expiry.
    revoked_tokens: Arc<RwLock<HashSet<String>>>,
    /// Optional OIDC manager.  Present only when `VAULT_OIDC_PROVIDERS` is
    /// configured at startup; `None` causes OIDC auth attempts to return
    /// `Status::unavailable`.
    oidc_manager: Option<Arc<OidcManager>>,
    /// Optional mTLS manager.  Present only when `VAULT_MTLS_ENABLED=true` is
    /// set at startup; `None` causes mTLS auth attempts to return
    /// `Status::unavailable`.
    mtls_manager: Option<Arc<MtlsManager>>,
    /// Optional AWS IAM auth manager.
    aws_iam_manager: Option<Arc<AwsIamManager>>,
    /// Optional Azure Workload Identity manager.
    azure_workload_manager: Option<Arc<AzureWorkloadManager>>,
}

impl IdentityServiceImpl {
    pub fn new(
        token_manager: TokenManager,
        store: PrincipalStore,
        oidc_manager: Option<Arc<OidcManager>>,
        mtls_manager: Option<Arc<MtlsManager>>,
        aws_iam_manager: Option<Arc<AwsIamManager>>,
        azure_workload_manager: Option<Arc<AzureWorkloadManager>>,
    ) -> Self {
        Self {
            token_manager,
            store,
            revoked_tokens: Arc::new(RwLock::new(HashSet::new())),
            oidc_manager,
            mtls_manager,
            aws_iam_manager,
            azure_workload_manager,
        }
    }

    /// Returns `true` when the raw token string has been explicitly revoked.
    fn is_revoked(&self, token: &str) -> bool {
        self.revoked_tokens
            .read()
            // Treat a poisoned lock as "not revoked" to avoid cascading
            // failures; the worst outcome is accepting a revoked token once.
            .map(|set| set.contains(token))
            .unwrap_or(false)
    }
}

#[tonic::async_trait]
impl IdentityService for IdentityServiceImpl {
    /// Authenticates a caller using the supplied method and issues a new JWT.
    ///
    /// Supported methods:
    /// - `TokenAuth`: validates an existing token and re-issues a fresh one.
    /// - `OidcAuth`: stub — not yet integrated with an OIDC provider.
    /// - `MtlsAuth`: validates a PEM-encoded X.509 client certificate against
    ///   the configured trusted CA and issues a token for the cert principal.
    async fn authenticate(
        &self,
        request: Request<AuthenticateRequest>,
    ) -> Result<Response<AuthenticateResponse>, Status> {
        let req = request.into_inner();

        if req.tenant_id.is_empty() {
            return Err(Status::invalid_argument("tenant_id must not be empty"));
        }

        let method = req.method.ok_or_else(|| {
            Status::invalid_argument("authenticate request must include an auth method")
        })?;

        // Resolve (principal_id, policies) from the supplied auth method.
        let (principal_id, policies): (String, Vec<String>) = match method {
            Method::Token(token_auth) => {
                if self.is_revoked(&token_auth.token) {
                    return Err(Status::unauthenticated("token has been revoked"));
                }

                let claims = self
                    .token_manager
                    .validate_token(&token_auth.token)
                    .map_err(vault_err_to_status)?;

                // Confirm the token belongs to the requested tenant.
                if claims.tenant_id != req.tenant_id {
                    warn!(
                        principal_id = %claims.sub,
                        token_tenant = %claims.tenant_id,
                        request_tenant = %req.tenant_id,
                        "tenant mismatch during token authentication"
                    );
                    return Err(Status::permission_denied(
                        "token does not belong to the requested tenant",
                    ));
                }

                (claims.sub, claims.policies)
            }
            Method::Oidc(oidc_auth) => {
                // Require that an OIDC manager is configured; return a clear
                // error if the operator has not set VAULT_OIDC_PROVIDERS.
                let manager = self
                    .oidc_manager
                    .as_ref()
                    .ok_or_else(|| Status::unavailable("OIDC authentication is not configured"))?;

                // Validate the caller-supplied ID token against the named
                // provider and extract the wslvault principal concepts.
                let result = manager
                    .validate_id_token(&oidc_auth.provider, &oidc_auth.id_token)
                    .await
                    .map_err(|e| Status::unauthenticated(format!("OIDC validation failed: {e}")))?;

                // Confirm the OIDC-derived tenant matches the requested tenant
                // to prevent cross-tenant token injection attacks.
                if result.tenant_id != req.tenant_id {
                    warn!(
                        provider = %oidc_auth.provider,
                        oidc_tenant = %result.tenant_id,
                        request_tenant = %req.tenant_id,
                        "OIDC tenant claim does not match requested tenant"
                    );
                    return Err(Status::permission_denied(
                        "OIDC tenant claim does not match the requested tenant",
                    ));
                }

                // Construct a stable, provider-scoped principal ID so the same
                // OIDC user always maps to the same wslvault principal across
                // logins.
                let principal_id = format!("oidc:{}:{}", oidc_auth.provider, result.subject);

                // Upsert the principal record — create on first login, silently
                // ignore the duplicate-key error on subsequent logins so the
                // principal is always registered before a token is issued.
                let record = PrincipalRecord {
                    id: principal_id.clone(),
                    tenant_id: result.tenant_id.clone(),
                    display_name: result.display_name.clone(),
                    auth_method: AuthMethod::Token,
                    policies: result.policies.clone(),
                    created_at: Utc::now(),
                };

                match self.store.create_principal(record) {
                    Ok(()) => {}
                    // A ValidationError means the principal was already
                    // registered on a prior login; that is expected.
                    Err(VaultError::ValidationError { .. }) => {}
                    Err(other) => return Err(vault_err_to_status(other)),
                }

                (principal_id, result.policies)
            }
            Method::AwsIam(aws_auth) => {
                let manager = self.aws_iam_manager.as_ref().ok_or_else(|| {
                    Status::unavailable("AWS IAM authentication is not configured")
                })?;

                let result = manager
                    .validate(
                        &aws_auth.iam_request_url,
                        &aws_auth.iam_request_body,
                        &aws_auth.iam_request_headers,
                        &aws_auth.bound_iam_role_arn,
                        &req.tenant_id,
                    )
                    .await
                    .map_err(|e| {
                        Status::unauthenticated(format!("AWS IAM validation failed: {e}"))
                    })?;

                // Cross-check tenant.
                if result.tenant_id != req.tenant_id {
                    warn!(
                        arn = %result.arn,
                        resolved_tenant = %result.tenant_id,
                        request_tenant = %req.tenant_id,
                        "AWS IAM tenant does not match requested tenant"
                    );
                    return Err(Status::permission_denied(
                        "AWS account does not map to the requested tenant",
                    ));
                }

                let principal_id = format!("aws:{}", result.arn);

                // Upsert the principal record.
                let record = PrincipalRecord {
                    id: principal_id.clone(),
                    tenant_id: result.tenant_id.clone(),
                    display_name: result.display_name.clone(),
                    auth_method: AuthMethod::AwsIam {
                        account_id: result.account_id.clone(),
                        arn: result.arn.clone(),
                    },
                    policies: result.policies.clone(),
                    created_at: Utc::now(),
                };

                match self.store.create_principal(record) {
                    Ok(()) => {}
                    Err(VaultError::ValidationError { .. }) => {}
                    Err(other) => return Err(vault_err_to_status(other)),
                }

                info!(
                    principal_id = %principal_id,
                    arn = %result.arn,
                    account_id = %result.account_id,
                    "AWS IAM principal authenticated"
                );

                (principal_id, result.policies)
            }
            Method::AzureWorkload(azure_auth) => {
                let manager = self.azure_workload_manager.as_ref().ok_or_else(|| {
                    Status::unavailable("Azure Workload Identity authentication is not configured")
                })?;

                let result = manager
                    .validate(
                        &azure_auth.jwt,
                        &azure_auth.azure_tenant_id,
                        &azure_auth.subscription_id,
                        &req.tenant_id,
                    )
                    .await
                    .map_err(|e| {
                        Status::unauthenticated(format!(
                            "Azure Workload Identity validation failed: {e}"
                        ))
                    })?;

                // Cross-check tenant.
                if result.tenant_id != req.tenant_id {
                    warn!(
                        object_id = %result.object_id,
                        resolved_tenant = %result.tenant_id,
                        request_tenant = %req.tenant_id,
                        "Azure tenant does not match requested tenant"
                    );
                    return Err(Status::permission_denied(
                        "Azure AD tenant does not map to the requested tenant",
                    ));
                }

                let principal_id = format!("azure:{}", result.object_id);

                // Upsert the principal record.
                let record = PrincipalRecord {
                    id: principal_id.clone(),
                    tenant_id: result.tenant_id.clone(),
                    display_name: result.display_name.clone(),
                    auth_method: AuthMethod::AzureWorkload {
                        object_id: result.object_id.clone(),
                        azure_tenant_id: result.azure_tenant_id.clone(),
                    },
                    policies: result.policies.clone(),
                    created_at: Utc::now(),
                };

                match self.store.create_principal(record) {
                    Ok(()) => {}
                    Err(VaultError::ValidationError { .. }) => {}
                    Err(other) => return Err(vault_err_to_status(other)),
                }

                info!(
                    principal_id = %principal_id,
                    object_id = %result.object_id,
                    azure_tenant = %result.azure_tenant_id,
                    "Azure Workload Identity principal authenticated"
                );

                (principal_id, result.policies)
            }
            Method::Mtls(mtls_auth) => {
                // Require that the mTLS manager was configured at startup.
                let manager = self
                    .mtls_manager
                    .as_ref()
                    .ok_or_else(|| Status::unavailable("mTLS authentication is not configured"))?;

                let result = manager
                    .validate_certificate(&mtls_auth.certificate_pem)
                    .map_err(|e| Status::unauthenticated(format!("mTLS validation failed: {e}")))?;

                // Prefix the principal id so it is distinguishable from other
                // auth methods in audit logs and policy evaluation.
                let mtls_principal_id = format!("mtls:{}", result.principal_id);

                // Verify that the tenant encoded in the certificate matches
                // the tenant_id supplied in the request, consistent with the
                // cross-check done for token-based authentication.
                if result.tenant_id != req.tenant_id {
                    warn!(
                        principal_id = %mtls_principal_id,
                        cert_tenant = %result.tenant_id,
                        request_tenant = %req.tenant_id,
                        "tenant mismatch during mTLS authentication"
                    );
                    return Err(Status::permission_denied(
                        "certificate tenant does not match the requested tenant",
                    ));
                }

                let lease_id = Uuid::now_v7().to_string();

                let (token, expires_at) = self
                    .token_manager
                    .issue_token(
                        &mtls_principal_id,
                        &result.tenant_id,
                        result.policies.clone(),
                        TOKEN_REISSUE_TTL_SECONDS,
                    )
                    .map_err(vault_err_to_status)?;

                info!(
                    principal_id = %mtls_principal_id,
                    tenant_id = %result.tenant_id,
                    serial = %result.serial_number,
                    display_name = %result.display_name,
                    expires_at = %expires_at,
                    "mTLS principal authenticated; token issued"
                );

                return Ok(Response::new(AuthenticateResponse {
                    token,
                    principal_id: mtls_principal_id,
                    tenant_id: result.tenant_id,
                    policies: result.policies,
                    expires_at: expires_at.timestamp(),
                    lease_id,
                }));
            }
        };

        let lease_id = Uuid::now_v7().to_string();

        let (new_token, expires_at) = self
            .token_manager
            .issue_token(
                &principal_id,
                &req.tenant_id,
                policies.clone(),
                TOKEN_REISSUE_TTL_SECONDS,
            )
            .map_err(vault_err_to_status)?;

        info!(
            principal_id = %principal_id,
            tenant_id = %req.tenant_id,
            expires_at = %expires_at,
            "principal authenticated; new token issued"
        );

        Ok(Response::new(AuthenticateResponse {
            token: new_token,
            principal_id,
            tenant_id: req.tenant_id,
            policies,
            expires_at: expires_at.timestamp(),
            lease_id,
        }))
    }

    /// Validates a JWT and returns the embedded principal information.
    ///
    /// Also checks the in-memory revocation set so that explicitly revoked
    /// tokens are rejected even before their natural expiry.
    async fn validate_token(
        &self,
        request: Request<ValidateTokenRequest>,
    ) -> Result<Response<ValidateTokenResponse>, Status> {
        let req = request.into_inner();

        if req.token.is_empty() {
            return Ok(Response::new(ValidateTokenResponse {
                valid: false,
                principal_id: String::new(),
                tenant_id: String::new(),
                policies: vec![],
            }));
        }

        // A revoked token is invalid regardless of its cryptographic validity.
        if self.is_revoked(&req.token) {
            return Ok(Response::new(ValidateTokenResponse {
                valid: false,
                principal_id: String::new(),
                tenant_id: String::new(),
                policies: vec![],
            }));
        }

        match self.token_manager.validate_token(&req.token) {
            Ok(claims) => Ok(Response::new(ValidateTokenResponse {
                valid: true,
                principal_id: claims.sub,
                tenant_id: claims.tenant_id,
                policies: claims.policies,
            })),
            Err(VaultError::Unauthenticated { .. }) => Ok(Response::new(ValidateTokenResponse {
                valid: false,
                principal_id: String::new(),
                tenant_id: String::new(),
                policies: vec![],
            })),
            Err(other) => Err(vault_err_to_status(other)),
        }
    }

    /// Adds a token to the in-memory revocation set.
    ///
    /// Once revoked the token will be rejected by both `authenticate` and
    /// `validate_token` for the lifetime of this process.  Revocations are
    /// not persisted across restarts in this initial implementation.
    async fn revoke_token(
        &self,
        request: Request<RevokeTokenRequest>,
    ) -> Result<Response<RevokeTokenResponse>, Status> {
        let req = request.into_inner();

        if req.token.is_empty() {
            return Err(Status::invalid_argument("token must not be empty"));
        }

        let mut set = self.revoked_tokens.write().map_err(|e| {
            error!(error = %e, "revocation set lock poisoned");
            Status::internal("internal lock error")
        })?;

        set.insert(req.token.clone());

        info!(
            token_prefix = &req.token[..req.token.len().min(20)],
            "token revoked"
        );

        Ok(Response::new(RevokeTokenResponse {}))
    }

    /// Creates a new service-account principal and issues an initial JWT.
    ///
    /// A service account is a machine identity with a stable principal_id and
    /// a set of policies.  The caller receives the principal_id, the initial
    /// token, and a lease_id for lease-tracking purposes.
    async fn create_service_account(
        &self,
        request: Request<CreateServiceAccountRequest>,
    ) -> Result<Response<CreateServiceAccountResponse>, Status> {
        let req = request.into_inner();

        if req.tenant_id.is_empty() {
            return Err(Status::invalid_argument("tenant_id must not be empty"));
        }
        if req.name.is_empty() {
            return Err(Status::invalid_argument("name must not be empty"));
        }

        let principal_id = Uuid::now_v7().to_string();
        let ttl_seconds = if req.ttl_seconds > 0 {
            req.ttl_seconds
        } else {
            DEFAULT_TTL_SECONDS
        };

        let record = PrincipalRecord {
            id: principal_id.clone(),
            tenant_id: req.tenant_id.clone(),
            display_name: req.name.clone(),
            auth_method: AuthMethod::MachineIdentity {
                service_account: req.name.clone(),
            },
            policies: req.policies.clone(),
            created_at: Utc::now(),
        };

        self.store
            .create_principal(record)
            .map_err(vault_err_to_status)?;

        let lease_id = Uuid::now_v7().to_string();

        let (token, _expires_at) = self
            .token_manager
            .issue_token(&principal_id, &req.tenant_id, req.policies, ttl_seconds)
            .map_err(vault_err_to_status)?;

        info!(
            principal_id = %principal_id,
            tenant_id = %req.tenant_id,
            name = %req.name,
            "service account created"
        );

        Ok(Response::new(CreateServiceAccountResponse {
            principal_id,
            token,
            lease_id,
        }))
    }

    /// Lists all service accounts (principals) registered for a tenant.
    async fn list_service_accounts(
        &self,
        request: Request<ListServiceAccountsRequest>,
    ) -> Result<Response<ListServiceAccountsResponse>, Status> {
        let req = request.into_inner();

        if req.tenant_id.is_empty() {
            return Err(Status::invalid_argument("tenant_id must not be empty"));
        }

        let records = self
            .store
            .list_principals(&req.tenant_id)
            .map_err(vault_err_to_status)?;

        let accounts: Vec<ServiceAccountInfo> = records
            .into_iter()
            .map(|r| ServiceAccountInfo {
                principal_id: r.id,
                name: r.display_name,
                policies: r.policies,
                // RFC 3339 string expected by the proto definition.
                created_at: r.created_at.to_rfc3339(),
            })
            .collect();

        Ok(Response::new(ListServiceAccountsResponse { accounts }))
    }
}
