//! identity-service binary entry point.
//!
//! Starts a combined tonic gRPC server (default port 50054) and an axum HTTP
//! server (default port 8080) serving health-check endpoints.  Both servers
//! run concurrently inside the same tokio runtime and honour the same
//! graceful-shutdown signal (SIGTERM or Ctrl-C).

use std::{net::SocketAddr, str::FromStr, sync::Arc};

use axum::Router;
use tokio::{signal, sync::oneshot};
use tonic::transport::Server;
use tracing::{error, info, warn};
use tracing_subscriber::{fmt, layer::SubscriberExt, util::SubscriberInitExt, EnvFilter};

mod api_keys;
mod aws_iam;
mod azure_workload;
mod grpc;
mod health;
mod mtls;
mod oidc;
mod openapi;
mod quota_handlers;
mod scim;
mod store;
mod tenant_handlers;
mod token;

/// Proto types generated by `tonic_build` at compile time via build.rs.
pub mod proto {
    tonic::include_proto!("wslvault.identity.v1");
}

use crate::{
    grpc::IdentityServiceImpl,
    mtls::{MtlsConfig, MtlsManager, SubjectMapping},
    oidc::{OidcManager, OidcProviderConfig},
    // `include_proto!("wslvault.identity.v1")` inlines the generated code
    // directly into `crate::proto` — there are no nested sub-modules.
    proto::identity_service_server::IdentityServiceServer,
    store::PrincipalStore,
    token::TokenManager,
};

/// Service configuration derived from environment variables at startup.
struct Config {
    /// Socket address for the gRPC listener.
    grpc_addr: SocketAddr,
    /// Socket address for the HTTP health listener.
    http_addr: SocketAddr,
    /// HMAC-SHA256 secret used to sign and verify JWTs.
    jwt_secret: Vec<u8>,
    /// Whether mTLS authentication is enabled (`VAULT_MTLS_ENABLED=true`).
    mtls_enabled: bool,
    /// Path to the PEM file containing trusted CA certificates
    /// (`VAULT_MTLS_CA_CERT_PATH`).  Required when `mtls_enabled` is `true`.
    mtls_ca_cert_path: Option<String>,
    /// Certificate subject field mapped to `tenant_id` (default: `"O"`).
    mtls_tenant_field: Option<String>,
    /// Certificate subject field mapped to `principal_id` (default: `"CN"`).
    mtls_principal_field: Option<String>,
    /// Comma-separated list of default policies granted to mTLS principals.
    mtls_default_policies: Option<Vec<String>>,
    /// Raw JSON string from `VAULT_OIDC_PROVIDERS`, or `None` when OIDC is
    /// not configured.  Parsed into provider configs during startup.
    oidc_providers_json: Option<String>,
}

impl Config {
    /// Reads configuration from environment variables with sensible defaults.
    ///
    /// Required variables:
    /// - `VAULT_JWT_SECRET`: raw bytes (UTF-8 string) used as the HMAC-SHA256 key.
    ///
    /// Optional variables:
    /// - `VAULT_LISTEN_ADDR`: gRPC listen address (default: `0.0.0.0:50054`).
    /// - `VAULT_HTTP_ADDR`: HTTP health listen address (default: `0.0.0.0:8080`).
    /// - `VAULT_MTLS_ENABLED`: set to `"true"` or `"1"` to enable mTLS auth.
    /// - `VAULT_MTLS_CA_CERT_PATH`: path to a PEM file with trusted CA cert(s).
    ///   Required when `VAULT_MTLS_ENABLED` is true.
    /// - `VAULT_MTLS_TENANT_FIELD`: cert subject field for tenant (default `"O"`).
    /// - `VAULT_MTLS_PRINCIPAL_FIELD`: cert subject field for principal (default `"CN"`).
    /// - `VAULT_MTLS_DEFAULT_POLICIES`: comma-separated default policy names.
    /// - `VAULT_OIDC_PROVIDERS`: JSON object mapping provider names to
    ///   `OidcProviderConfig` values (optional; OIDC disabled when absent).
    fn from_env() -> Result<Self, anyhow::Error> {
        let grpc_addr_str =
            std::env::var("VAULT_LISTEN_ADDR").unwrap_or_else(|_| "0.0.0.0:50054".to_string());
        let grpc_addr = SocketAddr::from_str(&grpc_addr_str)
            .map_err(|e| anyhow::anyhow!("invalid VAULT_LISTEN_ADDR '{grpc_addr_str}': {e}"))?;

        let http_addr_str =
            std::env::var("VAULT_HTTP_ADDR").unwrap_or_else(|_| "0.0.0.0:8080".to_string());
        let http_addr = SocketAddr::from_str(&http_addr_str)
            .map_err(|e| anyhow::anyhow!("invalid VAULT_HTTP_ADDR '{http_addr_str}': {e}"))?;

        let jwt_secret_str = std::env::var("VAULT_JWT_SECRET").map_err(|_| {
            anyhow::anyhow!("VAULT_JWT_SECRET environment variable is required but not set")
        })?;

        if jwt_secret_str.is_empty() {
            return Err(anyhow::anyhow!("VAULT_JWT_SECRET must not be empty"));
        }

        // mTLS is opt-in; any truthy value activates it.
        let mtls_enabled = matches!(
            std::env::var("VAULT_MTLS_ENABLED")
                .unwrap_or_default()
                .to_lowercase()
                .as_str(),
            "true" | "1" | "yes"
        );

        let mtls_ca_cert_path = std::env::var("VAULT_MTLS_CA_CERT_PATH").ok();

        // When mTLS is enabled the CA cert path is mandatory.
        if mtls_enabled && mtls_ca_cert_path.is_none() {
            return Err(anyhow::anyhow!(
                "VAULT_MTLS_CA_CERT_PATH is required when VAULT_MTLS_ENABLED is set"
            ));
        }

        let mtls_tenant_field = std::env::var("VAULT_MTLS_TENANT_FIELD").ok();
        let mtls_principal_field = std::env::var("VAULT_MTLS_PRINCIPAL_FIELD").ok();

        // Parse comma-separated default policies, ignoring empty segments.
        let mtls_default_policies = std::env::var("VAULT_MTLS_DEFAULT_POLICIES")
            .ok()
            .map(|raw| {
                raw.split(',')
                    .map(str::trim)
                    .filter(|s| !s.is_empty())
                    .map(String::from)
                    .collect::<Vec<String>>()
            })
            .filter(|v| !v.is_empty());

        // OIDC provider config is optional — store the raw JSON string here;
        // parsing and manager construction happen in `main()` so errors can
        // be logged with full context before the process exits.
        let oidc_providers_json = std::env::var("VAULT_OIDC_PROVIDERS").ok();

        Ok(Config {
            grpc_addr,
            http_addr,
            jwt_secret: jwt_secret_str.into_bytes(),
            mtls_enabled,
            mtls_ca_cert_path,
            mtls_tenant_field,
            mtls_principal_field,
            mtls_default_policies,
            oidc_providers_json,
        })
    }
}

#[tokio::main]
async fn main() -> Result<(), anyhow::Error> {
    // Initialise structured JSON logging.  Log level is controlled via the
    // standard `RUST_LOG` environment variable (default: info).
    tracing_subscriber::registry()
        .with(EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info")))
        .with(fmt::layer().json())
        .init();

    info!(
        version = env!("CARGO_PKG_VERSION"),
        "identity-service starting"
    );

    let config = Config::from_env().map_err(|e| {
        error!(error = %e, "failed to load configuration");
        e
    })?;

    let token_manager = TokenManager::new(&config.jwt_secret);
    // Clone the token manager before it is consumed by `IdentityServiceImpl`
    // so the same signing secret is available to the API key HTTP exchange endpoint.
    let token_manager_for_api_keys = token_manager.clone();
    let principal_store = PrincipalStore::new();
    // Clone before `principal_store` is moved into `IdentityServiceImpl` so
    // the SCIM handlers can share the same store for principal provisioning.
    let principal_store_for_scim = principal_store.clone();

    // Build the optional mTLS manager when mTLS authentication is enabled.
    let mtls_manager: Option<Arc<MtlsManager>> = if config.mtls_enabled {
        // `mtls_ca_cert_path` is guaranteed `Some` by `Config::from_env` when
        // `mtls_enabled` is `true`; the unwrap is therefore safe here.
        let ca_cert_path = config.mtls_ca_cert_path.as_deref().unwrap();

        let trusted_ca_pem = std::fs::read_to_string(ca_cert_path).map_err(|e| {
            anyhow::anyhow!(
                "failed to read mTLS CA certificate from '{ca_cert_path}': {e}"
            )
        })?;

        let mtls_config = MtlsConfig {
            trusted_ca_pem,
            subject_mapping: SubjectMapping {
                tenant_id_field: config.mtls_tenant_field.clone(),
                principal_id_field: config.mtls_principal_field.clone(),
                default_policies: config.mtls_default_policies.clone(),
            },
        };

        let manager = MtlsManager::new(mtls_config).map_err(|e| {
            anyhow::anyhow!("failed to initialise mTLS manager: {e}")
        })?;

        info!("mTLS authentication is enabled");
        Some(Arc::new(manager))
    } else {
        warn!("mTLS authentication is disabled (set VAULT_MTLS_ENABLED=true to enable)");
        None
    };

    // Build the optional OIDC manager from the JSON provider configuration.
    //
    // `VAULT_OIDC_PROVIDERS` is expected to be a JSON object whose keys are
    // provider names and whose values are `OidcProviderConfig` objects, e.g.:
    //
    // ```json
    // {
    //   "keycloak": {
    //     "issuer": "https://keycloak.example.com/realms/wslvault",
    //     "client_id": "wslvault",
    //     "claims_mapping": {
    //       "tenant_id_claim": "tenant_id",
    //       "policies_claim": "groups"
    //     }
    //   }
    // }
    // ```
    let oidc_manager: Option<Arc<OidcManager>> = match config.oidc_providers_json {
        Some(ref json) => {
            let providers: std::collections::HashMap<String, OidcProviderConfig> =
                serde_json::from_str(json).map_err(|e| {
                    anyhow::anyhow!(
                        "failed to parse VAULT_OIDC_PROVIDERS JSON: {e}"
                    )
                })?;

            if providers.is_empty() {
                warn!("VAULT_OIDC_PROVIDERS is set but contains no providers; OIDC disabled");
                None
            } else {
                info!(
                    provider_count = providers.len(),
                    providers = ?providers.keys().collect::<Vec<_>>(),
                    "OIDC authentication enabled"
                );
                Some(Arc::new(OidcManager::new(providers)))
            }
        }
        None => {
            warn!(
                "VAULT_OIDC_PROVIDERS is not set; \
                 OIDC authentication disabled (set it to enable)"
            );
            None
        }
    };

    // Build the optional AWS IAM manager from environment variables.
    let aws_iam_manager: Option<Arc<aws_iam::AwsIamManager>> = {
        let enabled = matches!(
            std::env::var("VAULT_AWS_IAM_ENABLED")
                .unwrap_or_default()
                .to_lowercase()
                .as_str(),
            "true" | "1" | "yes"
        );
        if enabled {
            let mut config = aws_iam::AwsIamConfig::default();
            if let Ok(endpoint) = std::env::var("VAULT_AWS_STS_ENDPOINT") {
                config.sts_endpoint = endpoint;
            }
            if let Ok(policies) = std::env::var("VAULT_AWS_IAM_DEFAULT_POLICIES") {
                config.default_policies = policies
                    .split(',')
                    .map(|s| s.trim().to_string())
                    .filter(|s| !s.is_empty())
                    .collect();
            }
            if let Ok(arns) = std::env::var("VAULT_AWS_IAM_BOUND_ROLE_ARNS") {
                config.bound_iam_role_arns = arns
                    .split(',')
                    .map(|s| s.trim().to_string())
                    .filter(|s| !s.is_empty())
                    .collect();
            }
            // Parse account→tenant mapping from JSON: {"123456789012":"tenant-uuid",...}
            if let Ok(mapping_json) = std::env::var("VAULT_AWS_ACCOUNT_TENANT_MAP") {
                if let Ok(map) = serde_json::from_str(&mapping_json) {
                    config.account_tenant_map = map;
                }
            }
            info!("AWS IAM authentication enabled");
            Some(Arc::new(aws_iam::AwsIamManager::new(config)))
        } else {
            warn!("AWS IAM authentication disabled (set VAULT_AWS_IAM_ENABLED=true to enable)");
            None
        }
    };

    // Build the optional Azure Workload Identity manager.
    let azure_workload_manager: Option<Arc<azure_workload::AzureWorkloadManager>> = {
        let enabled = matches!(
            std::env::var("VAULT_AZURE_WORKLOAD_ENABLED")
                .unwrap_or_default()
                .to_lowercase()
                .as_str(),
            "true" | "1" | "yes"
        );
        if enabled {
            let mut config = azure_workload::AzureWorkloadConfig::default();
            if let Ok(audience) = std::env::var("VAULT_AZURE_EXPECTED_AUDIENCE") {
                config.expected_audience = audience;
            }
            if let Ok(policies) = std::env::var("VAULT_AZURE_DEFAULT_POLICIES") {
                config.default_policies = policies
                    .split(',')
                    .map(|s| s.trim().to_string())
                    .filter(|s| !s.is_empty())
                    .collect();
            }
            if let Ok(subs) = std::env::var("VAULT_AZURE_BOUND_SUBSCRIPTION_IDS") {
                config.bound_subscription_ids = subs
                    .split(',')
                    .map(|s| s.trim().to_string())
                    .filter(|s| !s.is_empty())
                    .collect();
            }
            // Parse Azure tenant→wslvault tenant mapping from JSON
            if let Ok(mapping_json) = std::env::var("VAULT_AZURE_TENANT_MAP") {
                if let Ok(map) = serde_json::from_str(&mapping_json) {
                    config.azure_tenant_map = map;
                }
            }
            info!("Azure Workload Identity authentication enabled");
            Some(Arc::new(azure_workload::AzureWorkloadManager::new(config)))
        } else {
            warn!("Azure Workload Identity disabled (set VAULT_AZURE_WORKLOAD_ENABLED=true to enable)");
            None
        }
    };

    let identity_svc = IdentityServiceImpl::new(
        token_manager,
        principal_store,
        oidc_manager,
        mtls_manager,
        aws_iam_manager,
        azure_workload_manager,
    );
    let grpc_service = IdentityServiceServer::new(identity_svc);

    // Build the tenant store (database-backed when DATABASE_URL is set,
    // otherwise in-memory fallback).
    let tenant_store = tenant_handlers::TenantStoreState::from_env();

    // Build the API key manager and its associated HTTP state.
    // Uses the pre-cloned token manager so the API key exchange endpoint issues
    // JWTs with the same signing secret as the gRPC authentication flow.
    let api_key_state = api_keys::ApiKeyState {
        manager: api_keys::ApiKeyManager::new(),
        token_manager: token_manager_for_api_keys,
    };

    // Construct the SCIM shared state.  When DATABASE_URL is set, use
    // PostgreSQL for durable SCIM persistence; otherwise fall back to the
    // in-memory store (suitable for tests and single-instance dev).
    let scim_state = match std::env::var("DATABASE_URL") {
        Ok(database_url) if !database_url.is_empty() => {
            info!("SCIM: connecting to PostgreSQL for persistent storage");
            let scim_pool = sqlx::postgres::PgPoolOptions::new()
                .max_connections(5)
                .connect(&database_url)
                .await
                .map_err(|e| {
                    anyhow::anyhow!("failed to connect to PostgreSQL for SCIM: {e}")
                })?;
            let pg_store = scim::scim_store::PgScimStore::new(scim_pool);
            scim::ScimState::with_store(
                std::sync::Arc::new(pg_store),
                principal_store_for_scim,
            )
        }
        _ => {
            warn!("SCIM: DATABASE_URL not set; using in-memory store (data lost on restart)");
            scim::ScimState::new(principal_store_for_scim)
        }
    };

    // Build the quota management state.  Requires DATABASE_URL for the
    // PostgreSQL-backed tenant_quotas table; falls back to None (endpoints
    // return 503) when no database is configured.
    let quota_state = quota_handlers::QuotaState {
        pool: match std::env::var("DATABASE_URL") {
            Ok(url) if !url.is_empty() => {
                let quota_pool = sqlx::postgres::PgPoolOptions::new()
                    .max_connections(5)
                    .connect(&url)
                    .await
                    .map_err(|e| {
                        anyhow::anyhow!("failed to connect to PostgreSQL for quotas: {e}")
                    })?;
                Some(wslvault_storage::pool::DbPool::from_pool(quota_pool))
            }
            _ => {
                warn!("Quota management disabled: DATABASE_URL not set");
                None
            }
        },
    };

    // Build the HTTP router: health probes + tenant CRUD + API key endpoints
    // + SCIM 2.0 provisioning + quota management endpoints.
    //
    // Swagger UI is served at /swagger-ui (OpenAPI JSON at
    // /api-docs/openapi.json) for interactive API exploration.
    // SCIM endpoints are excluded from the OpenAPI doc — they follow RFC 7644
    // and are documented separately.
    use utoipa::OpenApi as _;
    use utoipa_swagger_ui::SwaggerUi;

    let http_app: Router = health::router()
        .merge(tenant_handlers::router(tenant_store))
        .merge(api_keys::router(api_key_state))
        .merge(quota_handlers::router(quota_state))
        .merge(scim::router().with_state(scim_state))
        .merge(
            SwaggerUi::new("/swagger-ui")
                .url("/api-docs/openapi.json", openapi::ApiDoc::openapi()),
        );

    // Shared shutdown channel: either server can trigger graceful shutdown.
    let (shutdown_tx, shutdown_rx) = oneshot::channel::<()>();

    // Spawn the gRPC server.
    let grpc_addr = config.grpc_addr;
    let grpc_handle = tokio::spawn(async move {
        info!(addr = %grpc_addr, "gRPC server listening");
        if let Err(e) = Server::builder()
            .add_service(grpc_service)
            .serve(grpc_addr)
            .await
        {
            error!(error = %e, "gRPC server error");
        }
    });

    // Spawn the HTTP server.
    let http_addr = config.http_addr;
    let http_handle = tokio::spawn(async move {
        info!(addr = %http_addr, "HTTP health server listening");
        let listener = match tokio::net::TcpListener::bind(http_addr).await {
            Ok(l) => l,
            Err(e) => {
                error!(error = %e, "failed to bind HTTP server");
                return;
            }
        };
        if let Err(e) = axum::serve(listener, http_app)
            .with_graceful_shutdown(async {
                // Wait for the shutdown signal to be sent.
                let _ = shutdown_rx.await;
            })
            .await
        {
            error!(error = %e, "HTTP server error");
        }
    });

    // Wait for OS shutdown signal then propagate graceful shutdown.
    wait_for_shutdown_signal().await;
    info!("shutdown signal received; stopping servers");

    // Signal the HTTP server to drain and stop.
    let _ = shutdown_tx.send(());

    // Await both servers; ignore join errors to ensure clean exit logging.
    let (grpc_result, http_result) = tokio::join!(grpc_handle, http_handle);

    if let Err(e) = grpc_result {
        error!(error = %e, "gRPC server task panicked");
    }
    if let Err(e) = http_result {
        error!(error = %e, "HTTP server task panicked");
    }

    info!("identity-service stopped");
    Ok(())
}

/// Waits for SIGTERM (Unix) or Ctrl-C (all platforms), whichever arrives first.
async fn wait_for_shutdown_signal() {
    let ctrl_c = async {
        signal::ctrl_c()
            .await
            .expect("failed to install Ctrl-C handler");
    };

    #[cfg(unix)]
    let sigterm = async {
        signal::unix::signal(signal::unix::SignalKind::terminate())
            .expect("failed to install SIGTERM handler")
            .recv()
            .await;
    };

    #[cfg(not(unix))]
    let sigterm = std::future::pending::<()>();

    tokio::select! {
        _ = ctrl_c => {},
        _ = sigterm => {},
    }
}
