//! identity-service binary entry point.
//!
//! Starts a combined tonic gRPC server (default port 50054) and an axum HTTP
//! server (default port 8080) serving health-check endpoints.  Both servers
//! run concurrently inside the same tokio runtime and honour the same
//! graceful-shutdown signal (SIGTERM or Ctrl-C).

use std::{net::SocketAddr, str::FromStr};

use axum::Router;
use tokio::{signal, sync::oneshot};
use tonic::transport::Server;
use tracing::{error, info};
use tracing_subscriber::{fmt, layer::SubscriberExt, util::SubscriberInitExt, EnvFilter};

mod grpc;
mod health;
mod store;
mod token;

/// Proto types generated by `tonic_build` at compile time via build.rs.
pub mod proto {
    tonic::include_proto!("wslvault.identity.v1");
}

use crate::{
    grpc::IdentityServiceImpl,
    // `include_proto!("wslvault.identity.v1")` inlines the generated code
    // directly into `crate::proto` — there are no nested sub-modules.
    proto::identity_service_server::IdentityServiceServer,
    store::PrincipalStore,
    token::TokenManager,
};

/// Service configuration derived from environment variables at startup.
struct Config {
    /// Socket address for the gRPC listener.
    grpc_addr: SocketAddr,
    /// Socket address for the HTTP health listener.
    http_addr: SocketAddr,
    /// HMAC-SHA256 secret used to sign and verify JWTs.
    jwt_secret: Vec<u8>,
}

impl Config {
    /// Reads configuration from environment variables with sensible defaults.
    ///
    /// Required variables:
    /// - `VAULT_JWT_SECRET`: raw bytes (UTF-8 string) used as the HMAC-SHA256 key.
    ///
    /// Optional variables:
    /// - `VAULT_LISTEN_ADDR`: gRPC listen address (default: `0.0.0.0:50054`).
    /// - `VAULT_HTTP_ADDR`: HTTP health listen address (default: `0.0.0.0:8080`).
    fn from_env() -> Result<Self, anyhow::Error> {
        let grpc_addr_str = std::env::var("VAULT_LISTEN_ADDR")
            .unwrap_or_else(|_| "0.0.0.0:50054".to_string());
        let grpc_addr = SocketAddr::from_str(&grpc_addr_str).map_err(|e| {
            anyhow::anyhow!("invalid VAULT_LISTEN_ADDR '{grpc_addr_str}': {e}")
        })?;

        let http_addr_str = std::env::var("VAULT_HTTP_ADDR")
            .unwrap_or_else(|_| "0.0.0.0:8080".to_string());
        let http_addr = SocketAddr::from_str(&http_addr_str).map_err(|e| {
            anyhow::anyhow!("invalid VAULT_HTTP_ADDR '{http_addr_str}': {e}")
        })?;

        let jwt_secret_str = std::env::var("VAULT_JWT_SECRET").map_err(|_| {
            anyhow::anyhow!(
                "VAULT_JWT_SECRET environment variable is required but not set"
            )
        })?;

        if jwt_secret_str.is_empty() {
            return Err(anyhow::anyhow!("VAULT_JWT_SECRET must not be empty"));
        }

        Ok(Config {
            grpc_addr,
            http_addr,
            jwt_secret: jwt_secret_str.into_bytes(),
        })
    }
}

#[tokio::main]
async fn main() -> Result<(), anyhow::Error> {
    // Initialise structured JSON logging.  Log level is controlled via the
    // standard `RUST_LOG` environment variable (default: info).
    tracing_subscriber::registry()
        .with(EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info")))
        .with(fmt::layer().json())
        .init();

    info!(version = env!("CARGO_PKG_VERSION"), "identity-service starting");

    let config = Config::from_env().map_err(|e| {
        error!(error = %e, "failed to load configuration");
        e
    })?;

    let token_manager = TokenManager::new(&config.jwt_secret);
    let principal_store = PrincipalStore::new();

    let identity_svc = IdentityServiceImpl::new(token_manager, principal_store);
    let grpc_service = IdentityServiceServer::new(identity_svc);

    // Build the HTTP health router.
    let http_app: Router = health::router();

    // Shared shutdown channel: either server can trigger graceful shutdown.
    let (shutdown_tx, shutdown_rx) = oneshot::channel::<()>();

    // Spawn the gRPC server.
    let grpc_addr = config.grpc_addr;
    let grpc_handle = tokio::spawn(async move {
        info!(addr = %grpc_addr, "gRPC server listening");
        if let Err(e) = Server::builder()
            .add_service(grpc_service)
            .serve(grpc_addr)
            .await
        {
            error!(error = %e, "gRPC server error");
        }
    });

    // Spawn the HTTP server.
    let http_addr = config.http_addr;
    let http_handle = tokio::spawn(async move {
        info!(addr = %http_addr, "HTTP health server listening");
        let listener = match tokio::net::TcpListener::bind(http_addr).await {
            Ok(l) => l,
            Err(e) => {
                error!(error = %e, "failed to bind HTTP server");
                return;
            }
        };
        if let Err(e) = axum::serve(listener, http_app)
            .with_graceful_shutdown(async {
                // Wait for the shutdown signal to be sent.
                let _ = shutdown_rx.await;
            })
            .await
        {
            error!(error = %e, "HTTP server error");
        }
    });

    // Wait for OS shutdown signal then propagate graceful shutdown.
    wait_for_shutdown_signal().await;
    info!("shutdown signal received; stopping servers");

    // Signal the HTTP server to drain and stop.
    let _ = shutdown_tx.send(());

    // Await both servers; ignore join errors to ensure clean exit logging.
    let (grpc_result, http_result) = tokio::join!(grpc_handle, http_handle);

    if let Err(e) = grpc_result {
        error!(error = %e, "gRPC server task panicked");
    }
    if let Err(e) = http_result {
        error!(error = %e, "HTTP server task panicked");
    }

    info!("identity-service stopped");
    Ok(())
}

/// Waits for SIGTERM (Unix) or Ctrl-C (all platforms), whichever arrives first.
async fn wait_for_shutdown_signal() {
    let ctrl_c = async {
        signal::ctrl_c()
            .await
            .expect("failed to install Ctrl-C handler");
    };

    #[cfg(unix)]
    let sigterm = async {
        signal::unix::signal(signal::unix::SignalKind::terminate())
            .expect("failed to install SIGTERM handler")
            .recv()
            .await;
    };

    #[cfg(not(unix))]
    let sigterm = std::future::pending::<()>();

    tokio::select! {
        _ = ctrl_c => {},
        _ = sigterm => {},
    }
}
