//! identity-service binary entry point.
//!
//! Starts a combined tonic gRPC server (default port 50054) and an axum HTTP
//! server (default port 8080) serving health-check endpoints.  Both servers
//! run concurrently inside the same tokio runtime and honour the same
//! graceful-shutdown signal (SIGTERM or Ctrl-C).

use std::{net::SocketAddr, str::FromStr, sync::Arc};

use axum::Router;
use tokio::{signal, sync::oneshot};
use tonic::transport::Server;
use tracing::{error, info, warn};
use tracing_subscriber::{fmt, layer::SubscriberExt, util::SubscriberInitExt, EnvFilter};

mod api_keys;
mod auth_methods;
mod aws_iam;
mod azure_workload;
mod crypto_client;
mod grpc;
mod health;
mod mfa;
mod mtls;
mod oidc;
mod openapi;
mod quota_handlers;
mod scim;
mod signing_keys;
mod store;
mod tenant_handlers;
mod token;

/// Proto types generated by `tonic_build` at compile time via build.rs.
pub mod proto {
    tonic::include_proto!("wslvault.identity.v1");
}

use crate::{
    grpc::IdentityServiceImpl,
    mtls::{MtlsConfig, MtlsManager, SubjectMapping},
    oidc::{OidcManager, OidcProviderConfig},
    // `include_proto!("wslvault.identity.v1")` inlines the generated code
    // directly into `crate::proto` — there are no nested sub-modules.
    proto::identity_service_server::IdentityServiceServer,
    store::PrincipalStore,
    token::TokenManager,
};

/// Service configuration derived from environment variables at startup.
struct Config {
    /// Socket address for the gRPC listener.
    grpc_addr: SocketAddr,
    /// Socket address for the HTTP health listener.
    http_addr: SocketAddr,
    /// HMAC-SHA256 secret used to sign and verify JWTs.
    jwt_secret: Vec<u8>,
    /// Issuer (`iss`) claim stamped into and validated on every JWT.
    jwt_issuer: String,
    /// Audience (`aud`) claim stamped into and validated on every JWT.
    jwt_audience: String,
    /// Whether mTLS authentication is enabled (`VAULT_MTLS_ENABLED=true`).
    mtls_enabled: bool,
    /// Path to the PEM file containing trusted CA certificates
    /// (`VAULT_MTLS_CA_CERT_PATH`).  Required when `mtls_enabled` is `true`.
    mtls_ca_cert_path: Option<String>,
    /// Certificate subject field mapped to `tenant_id` (default: `"O"`).
    mtls_tenant_field: Option<String>,
    /// Certificate subject field mapped to `principal_id` (default: `"CN"`).
    mtls_principal_field: Option<String>,
    /// Comma-separated list of default policies granted to mTLS principals.
    mtls_default_policies: Option<Vec<String>>,
    /// Raw JSON string from `VAULT_OIDC_PROVIDERS`, or `None` when OIDC is
    /// not configured.  Parsed into provider configs during startup.
    oidc_providers_json: Option<String>,
}

impl Config {
    /// Reads configuration from environment variables with sensible defaults.
    ///
    /// Required variables:
    /// - `VAULT_JWT_SECRET`: raw bytes (UTF-8 string) used as the HMAC-SHA256 key.
    ///
    /// Optional variables:
    /// - `VAULT_LISTEN_ADDR`: gRPC listen address (default: `0.0.0.0:50054`).
    /// - `VAULT_HTTP_ADDR`: HTTP health listen address (default: `0.0.0.0:8080`).
    /// - `VAULT_MTLS_ENABLED`: set to `"true"` or `"1"` to enable mTLS auth.
    /// - `VAULT_MTLS_CA_CERT_PATH`: path to a PEM file with trusted CA cert(s).
    ///   Required when `VAULT_MTLS_ENABLED` is true.
    /// - `VAULT_MTLS_TENANT_FIELD`: cert subject field for tenant (default `"O"`).
    /// - `VAULT_MTLS_PRINCIPAL_FIELD`: cert subject field for principal (default `"CN"`).
    /// - `VAULT_MTLS_DEFAULT_POLICIES`: comma-separated default policy names.
    /// - `VAULT_OIDC_PROVIDERS`: JSON object mapping provider names to
    ///   `OidcProviderConfig` values (optional; OIDC disabled when absent).
    fn from_env() -> Result<Self, anyhow::Error> {
        let grpc_addr_str =
            std::env::var("VAULT_LISTEN_ADDR").unwrap_or_else(|_| "0.0.0.0:50054".to_string());
        let grpc_addr = SocketAddr::from_str(&grpc_addr_str)
            .map_err(|e| anyhow::anyhow!("invalid VAULT_LISTEN_ADDR '{grpc_addr_str}': {e}"))?;

        let http_addr_str =
            std::env::var("VAULT_HTTP_ADDR").unwrap_or_else(|_| "0.0.0.0:8080".to_string());
        let http_addr = SocketAddr::from_str(&http_addr_str)
            .map_err(|e| anyhow::anyhow!("invalid VAULT_HTTP_ADDR '{http_addr_str}': {e}"))?;

        let jwt_secret_str = std::env::var("VAULT_JWT_SECRET").map_err(|_| {
            anyhow::anyhow!("VAULT_JWT_SECRET environment variable is required but not set")
        })?;

        // HS256 requires a high-entropy secret. A short secret is brute-forceable
        // offline from a single captured JWT, so enforce a 32-byte minimum.
        const MIN_JWT_SECRET_LEN: usize = 32;
        if jwt_secret_str.len() < MIN_JWT_SECRET_LEN {
            return Err(anyhow::anyhow!(
                "VAULT_JWT_SECRET must be at least {MIN_JWT_SECRET_LEN} bytes (got {})",
                jwt_secret_str.len()
            ));
        }

        // Issuer/audience bind tokens to this deployment, preventing replay of
        // tokens minted by a different WSLVault environment.
        let jwt_issuer = std::env::var("VAULT_JWT_ISSUER")
            .unwrap_or_else(|_| crate::token::DEFAULT_ISSUER.to_string());
        let jwt_audience = std::env::var("VAULT_JWT_AUDIENCE")
            .unwrap_or_else(|_| crate::token::DEFAULT_AUDIENCE.to_string());

        // mTLS is opt-in; any truthy value activates it.
        let mtls_enabled = matches!(
            std::env::var("VAULT_MTLS_ENABLED")
                .unwrap_or_default()
                .to_lowercase()
                .as_str(),
            "true" | "1" | "yes"
        );

        let mtls_ca_cert_path = std::env::var("VAULT_MTLS_CA_CERT_PATH").ok();

        // When mTLS is enabled the CA cert path is mandatory.
        if mtls_enabled && mtls_ca_cert_path.is_none() {
            return Err(anyhow::anyhow!(
                "VAULT_MTLS_CA_CERT_PATH is required when VAULT_MTLS_ENABLED is set"
            ));
        }

        let mtls_tenant_field = std::env::var("VAULT_MTLS_TENANT_FIELD").ok();
        let mtls_principal_field = std::env::var("VAULT_MTLS_PRINCIPAL_FIELD").ok();

        // Parse comma-separated default policies, ignoring empty segments.
        let mtls_default_policies = std::env::var("VAULT_MTLS_DEFAULT_POLICIES")
            .ok()
            .map(|raw| {
                raw.split(',')
                    .map(str::trim)
                    .filter(|s| !s.is_empty())
                    .map(String::from)
                    .collect::<Vec<String>>()
            })
            .filter(|v| !v.is_empty());

        // OIDC provider config is optional — store the raw JSON string here;
        // parsing and manager construction happen in `main()` so errors can
        // be logged with full context before the process exits.
        let oidc_providers_json = std::env::var("VAULT_OIDC_PROVIDERS").ok();

        Ok(Config {
            grpc_addr,
            http_addr,
            jwt_secret: jwt_secret_str.into_bytes(),
            jwt_issuer,
            jwt_audience,
            mtls_enabled,
            mtls_ca_cert_path,
            mtls_tenant_field,
            mtls_principal_field,
            mtls_default_policies,
            oidc_providers_json,
        })
    }
}

#[tokio::main]
async fn main() -> Result<(), anyhow::Error> {
    // ldap3 0.12 builds its rustls `ClientConfig` from the process-level
    // default provider. A `-p identity-service` build only enables rustls'
    // `ring` feature so rustls would pick it up on its own, but a workspace
    // build unifies in `aws_lc_rs` from the AWS SDK, leaving the choice
    // ambiguous and making the first LDAPS handshake panic. Pin it here.
    let _ = rustls::crypto::ring::default_provider().install_default();

    // Initialise structured JSON logging.  Log level is controlled via the
    // standard `RUST_LOG` environment variable (default: info).
    tracing_subscriber::registry()
        .with(EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info")))
        .with(fmt::layer().json())
        .init();

    info!(
        version = env!("CARGO_PKG_VERSION"),
        "identity-service starting"
    );

    // Expose Prometheus metrics for scraping (address via VAULT_METRICS_ADDR).
    wslvault_core::metrics::server::spawn_from_env();

    let config = Config::from_env().map_err(|e| {
        error!(error = %e, "failed to load configuration");
        e
    })?;

    let token_manager = TokenManager::with_issuer_audience(
        &config.jwt_secret,
        &config.jwt_issuer,
        &config.jwt_audience,
    );
    // Clone the token manager before it is consumed by `IdentityServiceImpl`
    // so the same signing secret is available to the API key HTTP exchange endpoint.
    let token_manager_for_api_keys = token_manager.clone();
    let principal_store = PrincipalStore::new();
    // Clone before `principal_store` is moved into `IdentityServiceImpl` so
    // the SCIM handlers can share the same store for principal provisioning.
    let principal_store_for_scim = principal_store.clone();

    // Build the optional mTLS manager when mTLS authentication is enabled.
    let mtls_manager: Option<Arc<MtlsManager>> = if config.mtls_enabled {
        // `mtls_ca_cert_path` is guaranteed `Some` by `Config::from_env` when
        // `mtls_enabled` is `true`; the unwrap is therefore safe here.
        let ca_cert_path = config.mtls_ca_cert_path.as_deref().unwrap();

        let trusted_ca_pem = std::fs::read_to_string(ca_cert_path).map_err(|e| {
            anyhow::anyhow!("failed to read mTLS CA certificate from '{ca_cert_path}': {e}")
        })?;

        let mtls_config = MtlsConfig {
            trusted_ca_pem,
            subject_mapping: SubjectMapping {
                tenant_id_field: config.mtls_tenant_field.clone(),
                principal_id_field: config.mtls_principal_field.clone(),
                default_policies: config.mtls_default_policies.clone(),
            },
        };

        let manager = MtlsManager::new(mtls_config)
            .map_err(|e| anyhow::anyhow!("failed to initialise mTLS manager: {e}"))?;

        info!("mTLS authentication is enabled");
        Some(Arc::new(manager))
    } else {
        warn!("mTLS authentication is disabled (set VAULT_MTLS_ENABLED=true to enable)");
        None
    };

    // Build the optional OIDC manager from the JSON provider configuration.
    //
    // `VAULT_OIDC_PROVIDERS` is expected to be a JSON object whose keys are
    // provider names and whose values are `OidcProviderConfig` objects, e.g.:
    //
    // ```json
    // {
    //   "keycloak": {
    //     "issuer": "https://keycloak.example.com/realms/wslvault",
    //     "client_id": "wslvault",
    //     "claims_mapping": {
    //       "tenant_id_claim": "tenant_id",
    //       "policies_claim": "groups"
    //     }
    //   }
    // }
    // ```
    let oidc_manager: Option<Arc<OidcManager>> = match config.oidc_providers_json {
        Some(ref json) => {
            let providers: std::collections::HashMap<String, OidcProviderConfig> =
                serde_json::from_str(json).map_err(|e| {
                    anyhow::anyhow!("failed to parse VAULT_OIDC_PROVIDERS JSON: {e}")
                })?;

            if providers.is_empty() {
                warn!("VAULT_OIDC_PROVIDERS is set but contains no providers; OIDC disabled");
                None
            } else {
                info!(
                    provider_count = providers.len(),
                    providers = ?providers.keys().collect::<Vec<_>>(),
                    "OIDC authentication enabled"
                );
                Some(Arc::new(OidcManager::new(providers)))
            }
        }
        None => {
            warn!(
                "VAULT_OIDC_PROVIDERS is not set; \
                 OIDC authentication disabled (set it to enable)"
            );
            None
        }
    };

    // Build the optional AWS IAM manager from environment variables.
    let aws_iam_manager: Option<Arc<aws_iam::AwsIamManager>> = {
        let enabled = matches!(
            std::env::var("VAULT_AWS_IAM_ENABLED")
                .unwrap_or_default()
                .to_lowercase()
                .as_str(),
            "true" | "1" | "yes"
        );
        if enabled {
            let mut config = aws_iam::AwsIamConfig::default();
            if let Ok(endpoint) = std::env::var("VAULT_AWS_STS_ENDPOINT") {
                config.sts_endpoint = endpoint;
            }
            if let Ok(policies) = std::env::var("VAULT_AWS_IAM_DEFAULT_POLICIES") {
                config.default_policies = policies
                    .split(',')
                    .map(|s| s.trim().to_string())
                    .filter(|s| !s.is_empty())
                    .collect();
            }
            if let Ok(arns) = std::env::var("VAULT_AWS_IAM_BOUND_ROLE_ARNS") {
                config.bound_iam_role_arns = arns
                    .split(',')
                    .map(|s| s.trim().to_string())
                    .filter(|s| !s.is_empty())
                    .collect();
            }
            // Parse account→tenant mapping from JSON: {"123456789012":"tenant-uuid",...}
            if let Ok(mapping_json) = std::env::var("VAULT_AWS_ACCOUNT_TENANT_MAP") {
                if let Ok(map) = serde_json::from_str(&mapping_json) {
                    config.account_tenant_map = map;
                }
            }
            info!("AWS IAM authentication enabled");
            Some(Arc::new(aws_iam::AwsIamManager::new(config).map_err(
                |e| {
                    error!(error = %e, "failed to build AWS IAM manager");
                    e
                },
            )?))
        } else {
            warn!("AWS IAM authentication disabled (set VAULT_AWS_IAM_ENABLED=true to enable)");
            None
        }
    };

    // Build the optional Azure Workload Identity manager.
    let azure_workload_manager: Option<Arc<azure_workload::AzureWorkloadManager>> = {
        let enabled = matches!(
            std::env::var("VAULT_AZURE_WORKLOAD_ENABLED")
                .unwrap_or_default()
                .to_lowercase()
                .as_str(),
            "true" | "1" | "yes"
        );
        if enabled {
            let mut config = azure_workload::AzureWorkloadConfig::default();
            if let Ok(audience) = std::env::var("VAULT_AZURE_EXPECTED_AUDIENCE") {
                config.expected_audience = audience;
            }
            if let Ok(policies) = std::env::var("VAULT_AZURE_DEFAULT_POLICIES") {
                config.default_policies = policies
                    .split(',')
                    .map(|s| s.trim().to_string())
                    .filter(|s| !s.is_empty())
                    .collect();
            }
            if let Ok(subs) = std::env::var("VAULT_AZURE_BOUND_SUBSCRIPTION_IDS") {
                config.bound_subscription_ids = subs
                    .split(',')
                    .map(|s| s.trim().to_string())
                    .filter(|s| !s.is_empty())
                    .collect();
            }
            // Parse Azure tenant→wslvault tenant mapping from JSON
            if let Ok(mapping_json) = std::env::var("VAULT_AZURE_TENANT_MAP") {
                if let Ok(map) = serde_json::from_str(&mapping_json) {
                    config.azure_tenant_map = map;
                }
            }
            info!("Azure Workload Identity authentication enabled");
            Some(Arc::new(
                azure_workload::AzureWorkloadManager::new(config).map_err(|e| {
                    error!(error = %e, "failed to build Azure Workload Identity manager");
                    e
                })?,
            ))
        } else {
            warn!("Azure Workload Identity disabled (set VAULT_AZURE_WORKLOAD_ENABLED=true to enable)");
            None
        }
    };

    // Clone oidc_manager before it is moved into the gRPC service, so the
    // device-flow router can share the same OIDC validation state.
    let oidc_manager_for_device = oidc_manager.clone();

    // Token revocations live in PostgreSQL so they survive restarts and are
    // visible to every replica. Without a database they fall back to an
    // in-process set, which IdentityServiceImpl::new warns loudly about.
    // One pool, two consumers: token revocation and per-tenant signing keys.
    // Cloned before either takes ownership.
    let revocation_pool = match std::env::var("DATABASE_URL") {
        Ok(url) if !url.is_empty() => {
            let pool = sqlx::postgres::PgPoolOptions::new()
                .max_connections(5)
                .connect(&url)
                .await
                .map_err(|e| {
                    anyhow::anyhow!("failed to connect to PostgreSQL for token revocation: {e}")
                })?;
            info!("token revocation: using PostgreSQL backend");
            Some(wslvault_storage::pool::DbPool::from_pool(pool))
        }
        _ => None,
    };

    // Reap revocations whose tokens have expired on their own; past a token's
    // own exp the JWT validator rejects it regardless, so the row is dead
    // weight. This is what keeps the table bounded.
    if let Some(pool) = revocation_pool.clone() {
        tokio::spawn(async move {
            let mut ticker = tokio::time::interval(std::time::Duration::from_secs(3600));
            loop {
                ticker.tick().await;
                match wslvault_storage::revocation_store::reap_expired(&pool).await {
                    Ok(0) => {}
                    Ok(n) => info!(reaped = n, "expired token revocations reaped"),
                    Err(e) => warn!(error = %e, "revocation reaper failed; will retry"),
                }
            }
        });
    }

    // Per-tenant Ed25519 signing keys need a database to keep them in and a
    // crypto-service to wrap them with. Without both, token issuance falls back
    // to the shared HS256 secret and warns on every token.
    let signing_key_pool = revocation_pool.clone();

    let identity_svc = IdentityServiceImpl::new(
        token_manager,
        principal_store,
        oidc_manager,
        mtls_manager,
        aws_iam_manager,
        azure_workload_manager,
        revocation_pool,
    );
    let grpc_service = IdentityServiceServer::new(identity_svc);

    // Build the tenant store (database-backed when DATABASE_URL is set,
    // otherwise in-memory fallback).
    let tenant_store = tenant_handlers::TenantStoreState::from_env().await?;

    // Build the API key manager and its associated HTTP state.
    // Uses the pre-cloned token manager so the API key exchange endpoint issues
    // JWTs with the same signing secret as the gRPC authentication flow.
    // Pre-clone the token manager so the new auth-method routers can share
    // the same signing key without re-creating the key material.
    let token_manager_for_auth_methods = token_manager_for_api_keys.clone();
    //
    // API keys live in PostgreSQL when DATABASE_URL is set. They used to live
    // in a process-local map, so every restart silently invalidated every key
    // ever issued and a second replica could not see the first replica's keys.
    let api_key_manager = match std::env::var("DATABASE_URL") {
        Ok(url) if !url.is_empty() => {
            let api_key_pool = sqlx::postgres::PgPoolOptions::new()
                .max_connections(5)
                .connect(&url)
                .await
                .map_err(|e| {
                    anyhow::anyhow!("failed to connect to PostgreSQL for api keys: {e}")
                })?;
            info!("api keys: using PostgreSQL backend");
            api_keys::ApiKeyManager::with_pool(wslvault_storage::pool::DbPool::from_pool(
                api_key_pool,
            ))
        }
        _ => {
            warn!("api keys: DATABASE_URL not set; using in-memory store (keys lost on restart)");
            api_keys::ApiKeyManager::new()
        }
    };

    // Key management is privilege-granting, so it carries its own authentication
    // rather than relying solely on the gateway-origin check: a deployment that
    // routes around the gateway, or leaves VAULT_GATEWAY_SECRET unset, would
    // otherwise expose key creation to anyone who can reach the port.

    let crypto_for_identity = std::env::var("CRYPTO_SERVICE_ENDPOINT")
        .ok()
        .filter(|e| !e.trim().is_empty())
        .map(|e| crypto_client::CryptoClient::new(e.trim()));

    let signing_keys = match (&signing_key_pool, std::env::var("CRYPTO_SERVICE_ENDPOINT")) {
        (Some(pool), Ok(endpoint)) if !endpoint.trim().is_empty() => {
            info!(endpoint = %endpoint, "per-tenant token signing keys enabled");
            Some(signing_keys::SigningKeys::new(
                pool.clone(),
                crypto_client::CryptoClient::new(endpoint.trim()),
            ))
        }
        _ => {
            warn!(
                "per-tenant signing keys are DISABLED (needs DATABASE_URL and \
                 CRYPTO_SERVICE_ENDPOINT). Tokens will be HS256 under the shared \
                 VAULT_JWT_SECRET, which every service that verifies them also holds."
            );
            None
        }
    };

    // The second factor needs a database for enrolments and the crypto-service
    // to wrap secrets with. Without both it is unavailable, and a key marked
    // mfa_required fails closed rather than quietly logging in without it.
    if signing_key_pool.is_none() || crypto_for_identity.is_none() {
        warn!(
            "authenticator (TOTP) MFA is DISABLED (needs DATABASE_URL and \
             CRYPTO_SERVICE_ENDPOINT); keys marked mfa_required will be refused"
        );
    }

    // Built after `signing_keys` so the admin gate can verify per-tenant EdDSA
    // tokens. Without them it falls back to HS256 only, which rejects every
    // token issued under per-tenant keys — every Bearer-authorised admin
    // operation would break silently.
    let admin_auth = api_keys::AdminAuth::from_env(token_manager_for_api_keys.clone())
        .with_signing_keys(signing_keys.clone());

    let api_key_state = api_keys::ApiKeyState {
        manager: api_key_manager,
        token_manager: token_manager_for_api_keys,
        signing_keys: signing_keys.clone(),
        mfa_pool: signing_key_pool.clone(),
        crypto: crypto_for_identity,
        challenges: mfa::ChallengeStore::new(),
    };

    // Construct the SCIM shared state.  When DATABASE_URL is set, use
    // PostgreSQL for durable SCIM persistence; otherwise fall back to the
    // in-memory store (suitable for tests and single-instance dev).
    let scim_state = match std::env::var("DATABASE_URL") {
        Ok(database_url) if !database_url.is_empty() => {
            info!("SCIM: connecting to PostgreSQL for persistent storage");
            let scim_pool = sqlx::postgres::PgPoolOptions::new()
                .max_connections(5)
                .connect(&database_url)
                .await
                .map_err(|e| anyhow::anyhow!("failed to connect to PostgreSQL for SCIM: {e}"))?;
            let pg_store = scim::scim_store::PgScimStore::new(scim_pool);
            scim::ScimState::with_store(std::sync::Arc::new(pg_store), principal_store_for_scim)
        }
        _ => {
            warn!("SCIM: DATABASE_URL not set; using in-memory store (data lost on restart)");
            scim::ScimState::new(principal_store_for_scim)
        }
    };

    // Build the quota management state.  Requires DATABASE_URL for the
    // PostgreSQL-backed tenant_quotas table; falls back to None (endpoints
    // return 503) when no database is configured.
    let quota_state = quota_handlers::QuotaState {
        pool: match std::env::var("DATABASE_URL") {
            Ok(url) if !url.is_empty() => {
                let quota_pool = sqlx::postgres::PgPoolOptions::new()
                    .max_connections(5)
                    .connect(&url)
                    .await
                    .map_err(|e| {
                        anyhow::anyhow!("failed to connect to PostgreSQL for quotas: {e}")
                    })?;
                Some(wslvault_storage::pool::DbPool::from_pool(quota_pool))
            }
            _ => {
                warn!("Quota management disabled: DATABASE_URL not set");
                None
            }
        },
    };

    // ── Build the optional LDAP manager ───────────────────────────────────────
    //
    // Enabled when `VAULT_LDAP_CONFIG` is set to a JSON-serialised
    // `LdapConfig` object.
    let ldap_router: Option<axum::Router> = match std::env::var("VAULT_LDAP_CONFIG") {
        Ok(json) if !json.is_empty() => {
            match serde_json::from_str::<auth_methods::ldap::LdapConfig>(&json) {
                Ok(ldap_config) => {
                    let manager =
                        std::sync::Arc::new(auth_methods::ldap::LdapManager::new(ldap_config));
                    let state = auth_methods::ldap::LdapState {
                        manager,
                        token_manager: token_manager_for_auth_methods.clone(),
                    };
                    info!("LDAP authentication enabled");
                    Some(auth_methods::ldap::router(state))
                }
                Err(e) => {
                    error!(error = %e, "failed to parse VAULT_LDAP_CONFIG; LDAP disabled");
                    None
                }
            }
        }
        _ => {
            warn!("LDAP authentication disabled (set VAULT_LDAP_CONFIG to enable)");
            None
        }
    };

    // ── Build the optional Kubernetes SA auth manager ─────────────────────────
    //
    // Enabled when `VAULT_K8S_CONFIG` is set to a JSON-serialised
    // `KubernetesConfig` object.
    let k8s_router: Option<axum::Router> = match std::env::var("VAULT_K8S_CONFIG") {
        Ok(json) if !json.is_empty() => {
            match serde_json::from_str::<auth_methods::kubernetes::KubernetesConfig>(&json) {
                Ok(k8s_config) => {
                    match auth_methods::kubernetes::KubernetesManager::new(k8s_config) {
                        Ok(manager) => {
                            let state = auth_methods::kubernetes::KubernetesState {
                                manager: std::sync::Arc::new(manager),
                                token_manager: token_manager_for_auth_methods.clone(),
                            };
                            info!("Kubernetes service-account authentication enabled");
                            Some(auth_methods::kubernetes::router(state))
                        }
                        Err(e) => {
                            error!(error = %e, "failed to build Kubernetes auth manager; K8s auth disabled");
                            None
                        }
                    }
                }
                Err(e) => {
                    error!(error = %e, "failed to parse VAULT_K8S_CONFIG; K8s auth disabled");
                    None
                }
            }
        }
        _ => {
            warn!(
                "Kubernetes service-account authentication disabled \
                 (set VAULT_K8S_CONFIG to enable)"
            );
            None
        }
    };

    // ── Build the optional OAuth2 device-flow manager ─────────────────────────
    //
    // Enabled when `VAULT_DEVICE_OIDC_CONFIG` is set to a JSON-serialised
    // `DeviceOidcConfig` object.  Requires OIDC to also be configured.
    let device_router: Option<axum::Router> = match std::env::var("VAULT_DEVICE_OIDC_CONFIG") {
        Ok(json) if !json.is_empty() => {
            match serde_json::from_str::<auth_methods::oauth_device::DeviceOidcConfig>(&json) {
                Ok(device_config) => {
                    if let Some(oidc_mgr) = &oidc_manager_for_device {
                        let manager = std::sync::Arc::new(
                            auth_methods::oauth_device::DeviceFlowManager::new(
                                device_config,
                                oidc_mgr.clone(),
                            ),
                        );
                        let state = auth_methods::oauth_device::DeviceFlowState {
                            manager,
                            token_manager: token_manager_for_auth_methods.clone(),
                        };
                        info!("OAuth2 device-flow authentication enabled");
                        Some(auth_methods::oauth_device::router(state))
                    } else {
                        warn!(
                            "VAULT_DEVICE_OIDC_CONFIG is set but VAULT_OIDC_PROVIDERS is not; \
                             device flow requires OIDC to be configured — disabling"
                        );
                        None
                    }
                }
                Err(e) => {
                    error!(error = %e, "failed to parse VAULT_DEVICE_OIDC_CONFIG; device flow disabled");
                    None
                }
            }
        }
        _ => {
            warn!(
                "OAuth2 device-flow authentication disabled \
                 (set VAULT_DEVICE_OIDC_CONFIG to enable)"
            );
            None
        }
    };

    // Build the HTTP router: health probes + tenant CRUD + API key endpoints
    // + SCIM 2.0 provisioning + quota management endpoints.
    //
    // Swagger UI is served at /swagger-ui (OpenAPI JSON at
    // /api-docs/openapi.json) for interactive API exploration.
    // SCIM endpoints are excluded from the OpenAPI doc — they follow RFC 7644
    // and are documented separately.
    use utoipa::OpenApi as _;
    use utoipa_swagger_ui::SwaggerUi;

    // Business routes trust tenant-identity headers, so they require
    // gateway-origin authentication (shared X-Gateway-Auth secret). Health
    // probes and the Swagger docs are intentionally left open.
    // Fold optional auth-method routers into the protected route set.
    // Each is `Option<Router>` — absent when the feature is not configured.
    let mut protected_routes: Router = tenant_handlers::router(tenant_store, admin_auth.clone())
        .merge(api_keys::router(api_key_state, admin_auth))
        .merge(quota_handlers::router(quota_state))
        .merge(scim::router().with_state(scim_state));

    if let Some(r) = ldap_router {
        protected_routes = protected_routes.merge(r);
    }
    if let Some(r) = k8s_router {
        protected_routes = protected_routes.merge(r);
    }
    if let Some(r) = device_router {
        protected_routes = protected_routes.merge(r);
    }

    let protected_routes: Router = protected_routes.layer(axum::middleware::from_fn_with_state(
        wslvault_core::middleware::GatewayAuth::from_env(),
        wslvault_core::middleware::require_gateway_auth,
    ));

    let http_app: Router = health::router().merge(protected_routes).merge(
        SwaggerUi::new("/swagger-ui").url("/api-docs/openapi.json", openapi::ApiDoc::openapi()),
    );

    // Shared shutdown channel: either server can trigger graceful shutdown.
    let (shutdown_tx, shutdown_rx) = oneshot::channel::<()>();

    // Spawn the gRPC server.
    let grpc_addr = config.grpc_addr;
    let grpc_handle = tokio::spawn(async move {
        info!(addr = %grpc_addr, "gRPC server listening");
        if let Err(e) = Server::builder()
            .add_service(grpc_service)
            .serve(grpc_addr)
            .await
        {
            error!(error = %e, "gRPC server error");
        }
    });

    // Spawn the HTTP server.
    let http_addr = config.http_addr;
    let http_handle = tokio::spawn(async move {
        info!(addr = %http_addr, "HTTP health server listening");
        let listener = match tokio::net::TcpListener::bind(http_addr).await {
            Ok(l) => l,
            Err(e) => {
                error!(error = %e, "failed to bind HTTP server");
                return;
            }
        };
        if let Err(e) = axum::serve(listener, http_app)
            .with_graceful_shutdown(async {
                // Wait for the shutdown signal to be sent.
                let _ = shutdown_rx.await;
            })
            .await
        {
            error!(error = %e, "HTTP server error");
        }
    });

    // Wait for OS shutdown signal then propagate graceful shutdown.
    wait_for_shutdown_signal().await;
    info!("shutdown signal received; stopping servers");

    // Signal the HTTP server to drain and stop.
    let _ = shutdown_tx.send(());

    // Await both servers; ignore join errors to ensure clean exit logging.
    let (grpc_result, http_result) = tokio::join!(grpc_handle, http_handle);

    if let Err(e) = grpc_result {
        error!(error = %e, "gRPC server task panicked");
    }
    if let Err(e) = http_result {
        error!(error = %e, "HTTP server task panicked");
    }

    info!("identity-service stopped");
    Ok(())
}

/// Waits for SIGTERM (Unix) or Ctrl-C (all platforms), whichever arrives first.
async fn wait_for_shutdown_signal() {
    let ctrl_c = async {
        signal::ctrl_c()
            .await
            .expect("failed to install Ctrl-C handler");
    };

    #[cfg(unix)]
    let sigterm = async {
        signal::unix::signal(signal::unix::SignalKind::terminate())
            .expect("failed to install SIGTERM handler")
            .recv()
            .await;
    };

    #[cfg(not(unix))]
    let sigterm = std::future::pending::<()>();

    tokio::select! {
        _ = ctrl_c => {},
        _ = sigterm => {},
    }
}
