//! Init command handler — interactive guided setup that writes ~/.wslvault/config.toml.

use crate::config::AppConfig;
use colored::Colorize;
use dialoguer::{Input, theme::ColorfulTheme};

pub async fn execute() -> anyhow::Result<()> {
    let config_path = AppConfig::config_path();

    eprintln!(
        "{} WSLVault interactive setup",
        "»".cyan().bold()
    );
    eprintln!(
        "  Config will be written to: {}\n",
        config_path.display().to_string().bold()
    );

    // Guard against accidentally overwriting an existing config.  Ask the user
    // explicitly rather than silently clobbering it.
    if config_path.exists() {
        eprintln!(
            "{} A config file already exists at {}.",
            "!".yellow().bold(),
            config_path.display()
        );
        let overwrite: String = Input::with_theme(&ColorfulTheme::default())
            .with_prompt("Overwrite it? [y/N]")
            .default("N".into())
            .interact_text()?;
        if !overwrite.trim().eq_ignore_ascii_case("y") {
            eprintln!("Aborted — existing config left unchanged.");
            return Ok(());
        }
    }

    let theme = ColorfulTheme::default();

    // Prompt for the vault endpoint URL
    let endpoint: String = Input::with_theme(&theme)
        .with_prompt("WSLVault endpoint URL")
        .default("http://localhost:8443".into())
        .interact_text()?;

    // Test connectivity before committing the config so the user gets immediate
    // feedback if the URL is wrong or the service is not running.
    eprint!("  Testing connectivity to {}... ", endpoint.bold());
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(5))
        .build()?;
    match client.get(format!("{}/health", endpoint)).send().await {
        Ok(resp) if resp.status().is_success() => {
            eprintln!("{}", "ok".green().bold());
        }
        Ok(resp) => {
            eprintln!("{} (status {})", "warning".yellow().bold(), resp.status());
            eprintln!(
                "  {} The server responded with a non-success status. Proceeding anyway.",
                "⚠".yellow()
            );
        }
        Err(e) => {
            eprintln!("{}", "failed".red().bold());
            eprintln!(
                "  {} Could not reach server: {}",
                "⚠".yellow(),
                e
            );
            let proceed: String = Input::with_theme(&theme)
                .with_prompt("Save config anyway? [y/N]")
                .default("N".into())
                .interact_text()?;
            if !proceed.trim().eq_ignore_ascii_case("y") {
                eprintln!("Aborted — no config written.");
                return Ok(());
            }
        }
    }

    // Build the minimal config and persist it.
    let config_content = format!(
        "# WSLVault configuration — generated by `wslvault init`\n\
         endpoint = \"{}\"\n\
         \n\
         [profiles.dev]\n\
         endpoint = \"http://localhost:8443\"\n\
         \n\
         [profiles.prod]\n\
         endpoint = \"https://vault.example.com\"\n",
        endpoint
    );

    // Ensure the parent directory exists before writing.
    if let Some(parent) = config_path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| {
            anyhow::anyhow!(
                "failed to create config directory {}: {}",
                parent.display(),
                e
            )
        })?;
    }
    std::fs::write(&config_path, &config_content).map_err(|e| {
        anyhow::anyhow!("failed to write config to {}: {}", config_path.display(), e)
    })?;

    eprintln!(
        "\n{} Config written to {}",
        "✓".green().bold(),
        config_path.display().to_string().bold()
    );
    eprintln!(
        "  Run {} to verify connectivity at any time.",
        "wslvault status".bold()
    );

    Ok(())
}
